phingofficial/phing

classes/phing/tasks/defaults.properties, classes/phing/tasks/system/DiagnosticsTask.php, docs/docbook5/en/source/appendixes/coretasks.xml
Runs phing's -diagnostics code inside phing itself.
=> Added DiagnosticsTask

classes/phing/tasks/system/condition/ConditionBase.php, classes/phing/tasks/system/condition/XorCondition.php, docs/docbook5/en/source/chapters/projcomponents.xml, test/classes/phing/tasks/condition/XorConditionTest.php, test/etc/tasks/system/XorConditionTest.xml
Added xor condition type for exclusive or operations.
=> Added xor condition

classes/phing/system/io/PhingFile.php, classes/phing/tasks/defaults.properties, classes/phing/tasks/system/Dirname.php, docs/docbook5/en/source/appendixes/coretasks.xml, test/classes/phing/tasks/system/DirnameTest.php, test/etc/tasks/system/DirnameTest.xml
```
<dirname property="foo.dirname" file="foo.txt"/>
```
will set `foo.dirname` to the project's basedir.
=> Added Dirname task

classes/phing/tasks/defaults.properties, classes/phing/tasks/ext/property/AbstractPropertySetterTask.php, classes/phing/tasks/ext/property/RegexTask.php, docs/docbook5/en/source/appendixes/optionaltasks.xml, test/classes/phing/tasks/ext/property/RegexTaskTest.php, test/etc/tasks/ext/property/RegExTaskTest.xml
Performs regular expression operations on an subject string, and sets the results to a property.
Inspired by http://ant-contrib.sourceforge.net/tasks/tasks/propertyregex.html
=> Added PropertyRegexTask

classes/phing/types/PatternSet.php
Assuming that it should be `PhingFile` instead.
=> Fixed "instanceof File" does not exist.

test/bootstrap.php
This makes it possible [for me, at least] to run PHPUnit from my IDE.
=> Use an absolute path (using __DIR__) in test/bootstrap.php

src/Io/Scanner/DirectoryScanner.php
Cherry-picks f84b028e47ca237f95817a109ed1f4aded177cc5 from `unstable-3.0`
=> DirectoryScanner refactorings

test/classes/phing/tasks/ext/ManifestTaskTest.php
Little fix for running ManifestTaskTest on windows systems.
=> Fixed test execution for ManifestTask on windows.

classes/phing/system/util/Properties.php, test/classes/phing/system/util/PropertiesTest.php, test/etc/system/util/test.properties, test/phpunit.xml
As one step to make sure we don't break things when merging #363.
=> Cleanup Properties class a little and add tests

test/ProjectTest.php
Well, really some first tests only.
=> Add first tests for Phing\Project

test/classes/phing/regression/320/Ticket320RegressionTest.php, test/etc/regression/320/build.xml
Cherry-picking from fb61ebe8960970d591c2943b3d1c1b3656d3cac5
=> Add regression test for http://www.phing.info/trac/ticket/320

test/classes/phing/regression/252/Ticket252RegressionTest.php, test/etc/regression/252/build.xml
Cherry-pick from fb61ebe8960970d591c2943b3d1c1b3656d3cac5
=> Improve regression test for Trac-252

src/Project.php
$userProperties actually need not keep the value, just the fact that a particular property is a user property.
=> Project.php minor cleanup

classes/phing/tasks/ext/FileSyncTask.php, docs/docbook5/en/source/appendixes/optionaltasks.xml
Add exclude option to rsync command.
=> Add exclude option to FileSyncTask.

classes/phing/system/util/Properties.php
BUILD FAILED
exception 'Phing\Io\IOException' with message 'Unable to write to empty filename' in /Users/htoda/Documents/src/payment-library/vendor/phing/phing/classes/phing/system/util/Properties.php:118
Stack trace:
#0 /Users/htoda/Documents/src/payment-library/vendor/phing/phing/classes/phing/tasks/ext/coverage/CoverageMerger.php(178): Properties->store()
#1 /Users/htoda/Documents/src/payment-library/vendor/phing/phing/classes/phing/tasks/ext/phpunit/PHPUnitTestRunner.php(162): CoverageMerger::merge(Object(Phing\Project), Array)
#2 /Users/htoda/Documents/src/payment-library/vendor/phing/phing/classes/phing/tasks/ext/phpunit/PHPUnitTask.php(500): PHPUnitTestRunner->run(Object(PHPUnit_Framework_TestSuite))
#3 /Users/htoda/Documents/src/payment-library/vendor/phing/phing/classes/phing/task …
=> Fix exception 'Phing\Io\IOException' with message 'Unable to write to empty filename' Error on phpunit task with codecoverage="true".

src/IntrospectionHelper.php
Cherry-pick 59f3839d6fae8fef9c46ee7d0e4b9fa063be89be from unstable-3.0
=> Heads-up for Task developers

docs/docbook5/en/source/appendixes/coretasks.xml
Cherry-pick 1e5e31d555cc05d505a7145dbc313c3711db9671
=> Clarification regarding http://www.phing.info/trac/ticket/637

classes/phing/types/PatternSet.php, test/classes/phing/regression/571/Ticket571RegressionTest.php, test/classes/phing/types/AbstractFileSetTest.php, test/classes/phing/types/PatternSetTest.php, test/etc/regression/571/build.xml, test/etc/types/patternset/patterns
This is the fix for http://www.phing.info/trac/ticket/571, cherry-picking c1b90d242a309021e3bde7ecb2cb4fd560944f44
and e4af553d14968bdd28431911d87a49f54efb0099 from unstable-3.0.
=> Support comma to separate expressions in DirectoryScanner (Trac-571)

classes/phing/tasks/system/PropertyTask.php, classes/phing/types/PropertyValue.php, src/Project.php, src/Util/Properties/PropertyFileReader.php, test/AbstractBuildFileTest.php, test/classes/phing/tasks/PropertyTaskTest.php, test/etc/system/util/filelist-1.properties, test/etc/system/util/filelist-2.properties, test/etc/tasks/property.xml, test/etc/tasks/property2.properties, test/phpunit.xml
This cherry-picks from 616e19b3e17c7d51fba8acbff0ef53211fe33c2c and fb61ebe8960970d591c2943b3d1c1b3656d3cac5.
=> Support FileList on PropertyTask, plus some test refactorings/additions

classes/phing/BuildLogger.php, classes/phing/Phing.php, classes/phing/listener/DefaultLogger.php
Added Ant like emacs mode.
```
$ phing -emacs
```
=> Added emacs mode

classes/phing/filters/SuffixLines.php, classes/phing/types/FilterChain.php, test/classes/phing/filters/SuffixLinesTest.php, test/etc/filters/expected/suffixlines.test, test/etc/filters/input/suffixlines.test, test/etc/filters/suffixlines.xml
As an addition to the PrefixLines filter...
=> Added SuffixLines filter

classes/phing/tasks/defaults.properties, classes/phing/tasks/ext/phar/PharDataTask.php, docs/docbook5/en/source/appendixes/optionaltasks.xml, test/classes/phing/tasks/ext/PharDataTaskTest.php, test/etc/tasks/ext/PharDataTaskTest.xml
Alternative archive maker task without a dependency like ArchiveTar but a minimum PHP version of 5.3 or the phar pecl is required.
http://php.net/manual/en/class.phardata.php
=> PharDataTask

classes/phing/tasks/ext/PhpCodeSnifferTask.php
=> Made show warnings work

classes/phing/tasks/ext/FtpDeployTask.php, docs/docbook5/en/source/appendixes/optionaltasks.xml
=> Added "skip on same size" to FtpDeployTask

classes/phing/tasks/ext/git/GitCloneTask.php, docs/docbook5/en/source/appendixes/optionaltasks.xml
=> add depth param to GitCloneTask

classes/phing/Phing.php, classes/phing/listener/SilentLogger.php
Example call:
```
$ phing -silent
```
=> Added silent argument

classes/phing/system/util/Properties.php, classes/phing/tasks/defaults.properties, classes/phing/tasks/system/EchoProperties.php, docs/docbook5/en/source/appendixes/coretasks.xml, test/classes/phing/tasks/system/EchoPropertiesTest.php, test/etc/tasks/system/EchoPropertiesTest.xml
Added EchoProperties Task see also https://ant.apache.org/manual/Tasks/echoproperties.html
Example:
```
<echoproperties format="xml" failonerror="false" destfile="properties.xml"/>
```
=> EchoProperties Task

classes/phing/tasks/defaults.properties, classes/phing/tasks/ext/inifile/IniFileConfig.php, classes/phing/tasks/ext/inifile/IniFileRemove.php, classes/phing/tasks/ext/inifile/IniFileSet.php, classes/phing/tasks/ext/inifile/IniFileTask.php, docs/docbook5/en/source/appendixes/optionaltasks.xml, test/classes/phing/tasks/ext/inifile/IniFileTaskTest.php, test/etc/tasks/ext/inifile/inifile.xml
Based on http://ant-contrib.sourceforge.net/tasks/tasks/inifile.html.
New pull request addressing issue logged at https://www.phing.info/trac/ticket/1193 - implementing ant inifile task ( http://ant-contrib.sourceforge.net/tasks/tasks/inifile.html ) for phing with some slight enhancements.
=> Add inifile task.

classes/phing/tasks/defaults.properties, classes/phing/tasks/system/Retry.php, docs/docbook5/en/source/appendixes/coretasks.xml, test/classes/phing/tasks/system/RetryTest.php, test/etc/tasks/system/RetryTest.xml
Added Ant like retry task as described here https://ant.apache.org/manual/Tasks/retry.html
Example:
```
<retry retrycount="3">
<httpget url="http://www.unreliable-server.com/unreliable.tar.gz" dir="/home/retry"/>
</retry>
```
=> Added retry task.

classes/phing/parser/Location.php
For better compatibility with PHP 7
=> Removed PHP4-style constructor

test/classes/phing/tasks/system/ApplyTaskTest.php
=> Fixed ApplyTaskTest::testSpawn()

test/classes/phing/regression/PhingCallAdhocTest.php, test/classes/phing/tasks/ext/pdepend/PhpDependTaskTest.php
Reduces the test output report on command line.
=> Avoid output on test run.

test/classes/phing/util/PearPackageScannerTest.php
=> Fixed pearPackageScannerTest

classes/phing/listener/ProfileLogger.php
Added ant like ProfileLogger.
```
$ phing -logger "phing.listener.ProfileLogger"
```
=> Added ProfileLogger

classes/phing/tasks/defaults.properties, classes/phing/tasks/system/TempFile.php, classes/phing/util/FileUtils.php, docs/docbook5/en/source/appendixes/coretasks.xml, test/classes/phing/tasks/system/TempFileTest.php, test/etc/tasks/system/TempFileTest.xml
Added ant like tempfiile task.
Example:
```
<tempfile property="temp.file" />
```
=> Added TempFile Task

classes/phing/tasks/ext/property/RegexTask.php, classes/phing/util/regexp/PregEngine.php, docs/docbook5/en/source/appendixes/optionaltasks.xml, test/classes/phing/tasks/ext/property/RegexTaskTest.php, test/etc/tasks/ext/property/RegExTaskTest.xml
PropertyRegexTask uses `Regexp()` now.
Fixed https://www.phing.info/trac/ticket/1190
=> Fixed https://www.phing.info/trac/ticket/1190

classes/phing/listener/TimestampedLogger.php
Added ant like `TimestampedLogger`
Example:
```
$ phing -logger "phing.listener.TimestampedLogger"
```
=> Added timestamped logger.

docs/docbook5/en/source/appendixes/optionaltasks.xml, docs/docbook5/en/source/chapters/settingup.xml
This the documentation for the Crap4jPHPUnitResultFormatter added in #422 by @Kerion.
=> Required documentation for crap4j formatter option to phpunit task (PR#422).

classes/phing/tasks/ext/FtpDeployTask.php
Depends on the pull request https://github.com/pear/Net_FTP/pull/3
=> Support SSL connection

classes/phing/tasks/ext/ZipTask.php, docs/docbook5/en/source/appendixes/optionaltasks.xml
Fixed https://www.phing.info/trac/ticket/1211
=> Added ignoreLinks flag to ZipTask

classes/phing/Phing.php
Added Ant like `-listener` argument.
```
$ phing -listener <classname>
```
=> Added listener argument to usage list.

classes/phing/tasks/system/ExecTask.php, classes/phing/tasks/system/condition/ConditionBase.php, classes/phing/tasks/system/condition/IsFailure.php, docs/docbook5/en/source/chapters/projcomponents.xml, test/classes/phing/tasks/condition/IsFailureTest.php, test/etc/tasks/system/IsFailureTest.xml
Example:
```
<target name="test">
<exec command="test" returnProperty="return.code"/>
<if>
<isfailure code="${return.code}"/>
<then><echo msg="${return.code}"/></then>
</if>
</target>
```
=> Added isFailure condition

classes/phing/tasks/system/ApplyTask.php, docs/docbook5/en/source/appendixes/coretasks.xml
ApplyTask with support for nested dirset elements.
=> ApplyTask - added support for dirsets.

classes/phing/tasks/ext/apigen/ApiGenTask.php, docs/docbook5/en/source/appendixes/optionaltasks.xml
Hey, I have updated Apigen to reflect Apigen API 4.1.
I am not sure if I changed documentation files correctly though...
=> Update of Apigen version 4.1

classes/phing/tasks/system/SwitchTask.php
=> Fixed php error using insensitive flag

classes/phing/tasks/ext/JsHintTask.php
=> Fixed execution on win with space in path

classes/phing/filters/PhpArrayMapLines.php, classes/phing/types/FilterChain.php
Applies a native php function to the original input.
Examples:
```
<phparraymaplines function="strtoupper"/>
```
```
<filterreader classname="phing.filters.PhpArrayMapLines">
<param name="function" value="strtoupper"/>
</filterreader>
```
=> PhpArrayMapLines

classes/phing/tasks/system/condition/ConditionBase.php, classes/phing/tasks/system/condition/IsPropertyFalseCondition.php, classes/phing/tasks/system/condition/IsPropertyTrueCondition.php, docs/docbook5/en/source/chapters/projcomponents.xml, test/classes/phing/BuildFileTest.php, test/classes/phing/tasks/condition/IsPropertyFalseConditionTest.php, test/classes/phing/tasks/condition/IsPropertyTrueConditionTest.php, test/etc/tasks/system/IsPropertyTrueFalseTest.xml
Added `<ispropertytrue property="foo"/>` and `<ispropertyfase property="foo"/>` condition.
```
<property name="test" value="yes" />
<if>
<ispropertytrue property="test"/>
<then>
<echo message="foo"/>
</then>
</if>
<if>
<ispropertyfalse property="test"/>
<then>
<echo message="bar"/>
</then>
</if>
```
=> Added IsPropertyFalse/-True conditions

classes/phing/tasks/system/MatchingTask.php, classes/phing/types/AbstractFileSet.php, classes/phing/types/selectors/BaseSelectorContainer.php, classes/phing/types/selectors/ReadableSelector.php, classes/phing/types/selectors/WritableSelector.php, docs/docbook5/en/source/appendixes/selectors.xml, test/classes/phing/types/selectors/ReadWriteTest.php, test/etc/types/selectors/ReadWriteTest.xml
Example usage:
```
<fileset dir="${src}" includes="**/*.php">
<readable/>
</fileset>
```
=> Added isReadable / isWritable selectors

classes/phing/tasks/ext/HttpTask.php
Fixed https://www.phing.info/trac/ticket/1237
=> Rethrow BuildException inside HttpTask

classes/phing/tasks/defaults.properties, classes/phing/tasks/ext/git/GitDescribeTask.php, docs/docbook5/en/source/appendixes/optionaltasks.xml, test/classes/phing/tasks/ext/GitTasks/GitDescribeTaskTest.php, test/etc/tasks/ext/git/GitDescribeTaskTest.xml
Tests and documentation will follow.
=> Added GitDescribeTask.

build/phing-stub.php
Hi,
It can be good to add an exit status code, to detect any initialization fail.
Don't you think?
=> Add an exit status code

classes/phing/util/DirectoryScanner.php
Added mercurial and bazaar related files to the default exclusion list.
=> Added mercurial and bazaar to the exclusion list.

classes/phing/tasks/defaults.properties, classes/phing/tasks/system/PathConvert.php, docs/docbook5/en/source/appendixes/coretasks.xml, test/classes/phing/tasks/system/PathConvertTest.php, test/etc/tasks/system/PathConvertTest.xml
Added ant like PathConvert task.
=> Added PathConvert task

classes/phing/listener/DefaultLogger.php
Logging of nested BuildExceptions.
=> Added logging output of errors caused by others.

classes/phing/Phing.php
I found that passing `-propertyfile <filename.yml>` was not setting the properties values as expected. The first reason for this was that the command option assumes that the file will use the IniParser. This has been addressed and did not support .yml files.
However, after adding yaml support I found that the expected property values still were not set. I'm not sure why. The passed `-propertyfile` was not overriding existing property values--merely defining new ones. Regardless, adding them to the $definedProps array seems to have solved it.
For background, I was using the `-f build.xml` option as well as loading various property files via the `<property file="<filename>" />` method. I'm not sure if this could be related.
=> Fixing -propertyfile option and adding yaml support for it.

classes/phing/tasks/system/MatchingTask.php, classes/phing/types/AbstractFileSet.php, classes/phing/types/selectors/BaseSelectorContainer.php, classes/phing/types/selectors/DifferentSelector.php, classes/phing/types/selectors/MappingSelector.php, classes/phing/types/selectors/SelectorContainer.php, docs/docbook5/en/source/appendixes/selectors.xml, test/classes/phing/types/selectors/DifferentSelectorTest.php, test/etc/types/selectors/DifferentSelectorTest.xml
Added ant like different selector.
=> Added different selector.

classes/phing/tasks/system/TstampTask.php, docs/docbook5/en/source/appendixes/coretasks.xml
Added timezone handling to the nested format element.
=> Added timezone to TstampTask

classes/phing/types/Commandline.php, docs/docbook5/en/source/appendixes/coretasks.xml
Fixed https://www.phing.info/trac/ticket/1243
=> Added escape attribute for ExecAttribute.

CREDITS.md, docs/docbook5/en/source/chapters/about.xml, docs/docbook5/en/source/master.xml
See the git log for details of what I've done since I first got involved, including updates to documentation, several optional tasks, bug fixes including the grammar RNG file etc.
=> Add myself, Ken Guest, to credits re work done.

classes/phing/tasks/ext/phpunit/PHPUnitTask.php, classes/phing/tasks/ext/phpunit/formatter/CloverPHPUnitResultFormatter.php, classes/phing/tasks/ext/phpunit/formatter/Crap4jPHPUnitResultFormatter.php
Fixes the phpunit-code-coverage version 4.x breaks the phing-tasks-phpunit component for ticket 1257
=> Fixed #1257: The phpunit-code-coverage version 4.x breaks the phing-tasks-phpunit component

classes/phing/tasks/system/condition/ConditionBase.php, classes/phing/tasks/system/condition/IsFileSelected.php, classes/phing/types/DataType.php, classes/phing/types/selectors/AbstractSelectorContainer.php, docs/docbook5/en/source/chapters/projcomponents.xml, test/classes/phing/tasks/condition/IsFileSelectedTest.php, test/etc/tasks/system/IsFileSelectedTest.xml
Added ant like IsFileSelected condition.
=> Added IsFileSelected condition.

classes/phing/tasks/system/AppendTask.php, classes/phing/tasks/system/AppendTask/TextElement.php, docs/docbook5/en/source/appendixes/coretasks.xml, etc/phing-grammar.rng, test/classes/phing/tasks/system/AppendTaskTest.php, test/etc/tasks/system/AppendTest.xml
Append task with new attributes:
- append
- overwrite
- fixlastline
- eol
New nested elements:
- header
- footer
- path
=> Added new function to append task.

classes/phing/tasks/system/LoadFileTask.php, docs/docbook5/en/source/appendixes/coretasks.xml
Added failonerror and quiet option to LoadFileTask.
=> LoadFileTask with failonerror and quiet option.

classes/phing/system/io/PhingFile.php, classes/phing/tasks/system/TouchTask.php, docs/docbook5/en/source/appendixes/coretasks.xml, test/classes/phing/tasks/system/TouchTaskTest.php, test/etc/tasks/system/TouchTaskTest.xml
Added mkdirs and verbose option to TouchTask.
=> TouchTask with mkdirs and verbose option

classes/phing/tasks/ext/JsHintTask.php
=> Added default initialization of xml attribs [JshintTask]

classes/phing/system/io/FileInputStream.php
Related to #597 - removed `$php_errormsg` in favor of better error hanmdling
=> Fixed undefined error variable

classes/phing/tasks/system/AppendTask.php
=> Added missing dir path

classes/phing/tasks/system/condition/ConditionBase.php, classes/phing/tasks/system/condition/Matches.php, docs/docbook5/en/source/chapters/projcomponents.xml, etc/phing-grammar.rng, test/classes/phing/tasks/system/ConditionTaskTest.php, test/etc/tasks/system/ConditionTest.xml
Simple regex condition:
``` xml
<condition property="matches">
<matches string="${subject}" pattern="package\.([^.]*)\.name" casesensitive="false" />
</condition>
```
=> Added matches condition

classes/phing/tasks/system/ConditionTask.php, docs/docbook5/en/source/appendixes/coretasks.xml, etc/phing-grammar.rng
Example:
```
<condition property="foo" else="bar">
<istrue value="false"/>
</condition>
<echo>${foo}</echo>
```
=> Added else attribute to ConditionTask

classes/phing/types/selectors/ContainsSelector.php, classes/phing/types/selectors/SelectorUtils.php, docs/docbook5/en/source/appendixes/selectors.xml
Whether to eliminate whitespace before checking the string in the text attribute.
=> Added ignorewhitespace attribut to contains selector.

classes/phing/tasks/ext/JsHintTask.php, docs/docbook5/en/source/appendixes/optionaltasks.xml
=> Added config setter to jshint.

classes/phing/tasks/system/AppendTask.php, docs/docbook5/en/source/appendixes/coretasks.xml
=> Fixed default behavior of append

classes/phing/system/io/YamlFileParser.php
=> Throws exception if dependency is not installed correctly.

.gitattributes
this helps executing docs/docbook5/en/scripts/deb-setup.sh
=> *.sh eol=lf (enforce unix line ending for shell scripts)

classes/phing/ProjectComponent.php, classes/phing/Task.php, classes/phing/parser/Location.php, classes/phing/tasks/ext/VersionTask.php, classes/phing/tasks/ext/creole/CreoleSQLExecTask.php, classes/phing/tasks/ext/creole/CreoleTask.php, classes/phing/tasks/ext/pdo/PDOSQLExecTask.php, classes/phing/tasks/ext/pdo/PDOTask.php, classes/phing/tasks/ext/rSTTask.php, classes/phing/tasks/system/AdhocTaskdefTask.php, classes/phing/tasks/system/AdhocTypedefTask.php, classes/phing/tasks/system/AvailableTask.php, classes/phing/tasks/system/CopyTask.php, classes/phing/tasks/system/DeleteTask.php, classes/phing/tasks/system/ForeachTask.php, classes/phing/tasks/system/ImportTask.php, classes/phing/tasks/system/MkdirTask.php, classes/phing/tasks/system/MoveTask.php, classes/phing/tasks/system/PhpEvalTask.php, classes/phing/tasks/system/TouchTask.php, classes/phing/tasks/system/UpToDateTask.php, classes/phing/types/DataType.php
- Fixed vgerbose msg in import task
- Moved description and location to project component
- Used getter in favor of property
=> Fixed verbose msg in import task

classes/phing/tasks/ext/VersionTask.php, docs/docbook5/en/source/appendixes/optionaltasks.xml, test/classes/phing/tasks/ext/VersionTaskTest.php, test/etc/tasks/ext/version.xml
Added property file generation and made file name and property optional.
=> Added property file generation for VersionTask

classes/phing/tasks/defaults.properties, classes/phing/tasks/ext/property/SortList.php, docs/docbook5/en/source/appendixes/optionaltasks.xml, test/classes/phing/tasks/ext/property/SortListTest.php, test/etc/tasks/ext/property/SortListTest.xml
Added sortlist task for properties http://ant-contrib.sourceforge.net/tasks/tasks/sortlist.html
=> Added sortlist task for properties.

bin/phing.php
Added improved color determination under windows.
=> No colored output under windows 10 inside powershell.

composer.json
Updating composer.json support node
=> Updating composer.json

classes/phing/tasks/defaults.properties, classes/phing/tasks/system/RunTargetTask.php, docs/docbook5/en/source/appendixes/coretasks.xml, test/classes/phing/tasks/system/RunTargetTaskTest.php, test/etc/tasks/system/RunTargetTaskTest.xml
Phing task that runs a target:
``` xml
<target name="run">
<runtarget target="anotherTarget" />
</target>
<target name="anotherTarget">
<echo msg="THIS COMES FROM ANOTHER TARGET"/>
</target>
```
=> Added runtarget task.

classes/phing/tasks/defaults.properties, classes/phing/tasks/ext/property/Variable.php, docs/docbook5/en/source/appendixes/optionaltasks.xml, test/classes/phing/tasks/ext/property/VariableTest.php, test/etc/tasks/ext/property/VariableTest.xml
Added ant contrib like variable task.
See: http://ant-contrib.sourceforge.net/tasks/tasks/variable_task.html
=> Added variable task.

classes/phing/system/io/Win32FileSystem.php
Added missing method which is required by `MoveTask` and `DeleteTask` for win systems.
=> Added Win32FileSystem::listContents()

appveyor.yml
Added appveyor configuration yaml to support [appveyor](https://www.appveyor.com/) service.
It is a continuous delivery service for windows where tests could be executed.
=> Added appveyor config.

classes/phing/tasks/system/condition/HttpCondition.php, docs/docbook5/en/source/chapters/projcomponents.xml
Added `requestmethod` and `followredirects` attributes to the `<http>` condition.
=> Added requestmethod and followredirects for http condition.

classes/phing/Target.php, classes/phing/tasks/system/MatchingTask.php, classes/phing/types/selectors/SelectorAware.php, classes/phing/types/selectors/SelectorContainer.php, classes/phing/types/selectors/SymlinkSelector.php, docs/docbook5/en/source/appendixes/selectors.xml, test/classes/phing/types/selectors/SymlinkSelectorTest.php, test/etc/types/selectors/SymlinkSelectorTest.xml
=> Added symlink selector.

classes/phing/system/io/PhingFile.php, classes/phing/tasks/system/MatchingTask.php, classes/phing/types/selectors/ExecutableSelector.php, classes/phing/types/selectors/SelectorAware.php, classes/phing/types/selectors/SelectorContainer.php, docs/docbook5/en/source/appendixes/selectors.xml, test/classes/phing/types/selectors/ExecutableTest.php, test/etc/types/selectors/ExecutableTest.xml
=> Added executable selector.

docs/docbook5/en/source/appendixes/coretasks.xml, docs/docbook5/en/source/appendixes/coretypes.xml, etc/phing-grammar.rng
=> Added documentation and grammer for #649

classes/phing/tasks/defaults.properties, classes/phing/tasks/ext/property/PropertySelector.php, docs/docbook5/en/source/appendixes/optionaltasks.xml, etc/phing-grammar.rng, test/classes/phing/tasks/ext/property/PropertySelectorTest.php, test/etc/tasks/ext/property/PropertySelectorTest.xml
See http://ant-contrib.sourceforge.net/tasks/tasks/propertyselector.html
=> Added ant contrib like PropertySelector task

classes/phing/types/Path.php
Just the adder was missing to fully support filelists.
=> Added missing filelist adder.

classes/phing/tasks/ext/HttpRequestTask.php
=> Added support for application/json to HttpRequestTask

docs/docbook5/en/source/appendixes/coretasks.xml
=> Documentation: Fixed a typo

classes/phing/filters/TranslateGettext.php, classes/phing/listener/NoBannerLogger.php, classes/phing/tasks/ext/ComposerTask.php, classes/phing/tasks/ext/coverage/CoverageSetupTask.php, classes/phing/tasks/ext/dbdeploy/DbDeployTask.php, classes/phing/tasks/ext/inifile/IniFileTask.php, classes/phing/tasks/ext/liquibase/LiquibaseRollbackTask.php, classes/phing/tasks/ext/liquibase/LiquibaseTagTask.php, classes/phing/tasks/ext/property/PropertySelector.php, classes/phing/tasks/system/ApplyTask.php, classes/phing/tasks/system/AttribTask.php, classes/phing/types/AbstractFileSet.php, classes/phing/util/DirectoryScanner.php, classes/phing/util/SourceFileScanner.php
- Minor code tweaks (regex, language level migration)
- suspicious assignments
- bugfixes (misplaced operator, class/file names mismatch)
=> SCA with Php Inspections (EA Extended)

classes/phing/tasks/ext/phploc/PHPLocCSVFormatter.php, classes/phing/tasks/ext/phploc/PHPLocXMLFormatter.php, composer.json, composer.lock
This PR solves formatting issues when using PHPLoc 4.
Fixed #725 
Fixed #724
=> Added PHPLoc ^4 support.

classes/phing/system/io/FileSystem.php, classes/phing/tasks/ext/SassTask.php, classes/phing/tasks/ext/rSTTask.php, test/classes/phing/system/io/FileSystemTest.php, test/classes/phing/tasks/ext/rST/rSTTaskTest.php
This could also be used in the rST task, instead of requiring PEAR's System class.
@cweiske - what do you think? I value your opinion as you are both the originator of the rST task, a phing maintainer and a stalwart of the PEAR project :-)
=> Add "which" method to FileSystem class, for solving Issue 710.

classes/phing/tasks/ext/dbdeploy/DbDeployTask.php
Allow splitting on --//@UNDO with multiple spaces and without spaces.
Ignore tabs and spaces between -- and //@UNDO and any characters after @UNDO in that line.
=> DBDeploy improved splitting on --//@UNDO

classes/phing/tasks/ext/Service/Amazon.php, classes/phing/tasks/ext/Service/Amazon/S3.php, classes/phing/tasks/ext/Service/Amazon/S3/S3GetTask.php, classes/phing/tasks/ext/Service/Amazon/S3/S3PutTask.php, composer.json, composer.lock
=> Superseded #302 Remove S3 PEAR dependency

classes/phing/tasks/ext/ioncube/IoncubeEncoderTask.php
Updated IoncubeEncoderTask for version 10 and php7.1
=> Updated IoncubeEncoderTask.php

docs/docbook5/en/source/appendixes/coretasks.xml
This new example shows how to echo a fileset element.
=> Add new example for EchoTask

.travis.sh
Related to https://github.com/travis-ci/travis-ci/issues/8365
=> Fixed php dir setting on travis.

docs/docbook5/en/source/chapters/projcomponents.xml
I added more details about HasFreeSpace condition.
=> Enhance HasFreeSpace condition documentation

classes/phing/tasks/ext/StopwatchTask.php
=> Added stopwatch name to log output.

classes/phing/Project.php, classes/phing/PropertyHelper.php, classes/phing/Target.php, classes/phing/filters/ExpandProperties.php, classes/phing/parser/ProjectConfigurator.php, classes/phing/tasks/ext/pdo/DefaultPDOQuerySplitter.php, classes/phing/tasks/ext/pdo/DummyPDOQuerySplitter.php, classes/phing/tasks/ext/pdo/PgsqlPDOQuerySplitter.php, classes/phing/tasks/ext/property/Variable.php, classes/phing/tasks/system/PropertyTask.php
Extracted all property related stuff to a `PropertyHelper`.
=> Added PropertyHelper.

classes/phing/tasks/ext/StopwatchTask.php, composer.json
=> Added additional autoloader stmt and more clarification to the StopwatchTask

classes/phing/tasks/system/CopyTask.php, docs/docbook5/en/source/appendixes/coretasks.xml, etc/phing-grammar.rng
- added flatten setter
- added flatten attrib to the docu
- call parent constructor
=> Added flatten setter to the copy task and documentation.

classes/phing/tasks/system/ExecTask.php, classes/phing/tasks/system/condition/OsCondition.php, docs/docbook5/en/source/appendixes/coretasks.xml, etc/phing-grammar.rng, test/classes/phing/tasks/system/ExecTaskTest.php, test/etc/tasks/system/ExecTest.xml
* Added osfamily attribute to ExecTask
* Added tests and documentation
* Extended grammar file for missing `<os>` and `<exec>` info
=> Added osfamily attribute to ExecTask

classes/phing/filters/LineContainsRegexp.php, docs/docbook5/en/source/appendixes/corefilters.xml, etc/phing-grammar.rng, test/classes/phing/filters/LineContainsRegexpTest.php, test/etc/filters/expected/linecontainsregexp-negate.test, test/etc/filters/linecontainsregexp.xml
Example:
```xml
<linecontainsregexp regexp="FOO*" casesensitive="false" negate="true" />
```
=> Added negate, regexp, casesensitive attribs to linecontainsregexp filter

classes/phing/tasks/ext/phpunit/FormatterElement.php, classes/phing/tasks/ext/phpunit/PHPUnitTask.php, classes/phing/tasks/ext/phpunit/PHPUnitTestRunner6.php, classes/phing/tasks/ext/phpunit/formatter/Crap4jPHPUnitResultFormatter.php, classes/phing/tasks/ext/phpunit/formatter5/CloverPHPUnitResultFormatter5.php, classes/phing/tasks/ext/phpunit/formatter5/Crap4jPHPUnitResultFormatter5.php, classes/phing/tasks/ext/phpunit/formatter5/PHPUnitResultFormatter5.php, classes/phing/tasks/ext/phpunit/formatter5/PlainPHPUnitResultFormatter5.php, classes/phing/tasks/ext/phpunit/formatter5/SummaryPHPUnitResultFormatter5.php, classes/phing/tasks/ext/phpunit/formatter5/XMLPHPUnitResultFormatter5.php, composer.lock
=> Added phpunit 6 support.

composer.json
This PR adds support for Symfony 4.0 components to composer.json 
#SymfonyConHackday2017
=> Support Symfony 4.0

classes/phing/tasks/defaults.properties, classes/phing/tasks/ext/git/GitArchiveTask.php, docs/docbook5/en/source/appendixes/optionaltasks.xml, etc/phing-grammar.rng, test/classes/phing/tasks/ext/GitTasks/GitArchiveTaskTest.php, test/etc/tasks/ext/git/GitArchiveTaskTest.xml
=> Added git archive task.

classes/phing/tasks/ext/ParallelTask.php, composer.json, composer.lock
Fixed the composer installation issue described in #799 and #814
=> Fixed composer install issue

docs/docbook5/en/source/chapters/about.xml
and added myself to the about section.
=> Changed copyright year to 2018

docs/docbook5/en/source/appendixes/optionaltasks.xml
Added port section - related to #808
=> Updated documentation - FileSyncTask

classes/phing/tasks/system/PhingTask.php, classes/phing/tasks/system/PropertyTask.php
Reinit should cover logoutput and quiet mode as well.
=> Fixed missing attributes on reinit of properties in PhingTask.

classes/phing/tasks/system/PhingTask.php
As a preparation for future implementation of sub-projects.
=> Extracted method

.gitattributes
Related to https://github.com/phingofficial/phing/commit/189b49f8e74e50cf509d9ab261856a9b52515ff7
=> Removed unused ident

docs/api/build.xml
Added improved function to the API build file:
* Added description used by `phing -projecthelp`
* Added user property to choose a template `phing -Dtemplate=clean build`
* Take care of build in function instead of calling `php`
=> Optimized api build file

classes/phing/tasks/ext/zendguard/ZendGuardFileSet.php
Related #835 and reportet by @MaXal thx
=> Fixed FatalError in ZendGuardFileSet

test/classes/phing/regression/309/Ticket309RegressionTest.php
=> Fixed regression test 309 for win

classes/phing/input/ConsoleInputHandler.php
=> Fixed ConsoleInputHandler for symfony 4

classes/phing/IntrospectionHelper.php
=> Fixed #887

classes/phing/types/selectors/ContainsRegexpSelector.php, classes/phing/types/selectors/ContainsSelector.php
=> Fixes #560

classes/phing/system/io/FileParserFactory.php, classes/phing/system/io/XmlFileParser.php, classes/phing/tasks/ext/XmlPropertyTask.php, docs/guide/en/source/appendixes/fileformats.xml
* Moved file loading to a new `XmlFileParser`
* Made `XmlFileParser` available in the `FileParserFactory`
=> Made XML based property files loadable.

classes/phing/tasks/system/ExecTask.php, classes/phing/types/Environment.php, classes/phing/types/environment/EnvVariable.php, docs/guide/en/source/appendixes/coretasks.xml, etc/phing-grammar.rng, test/classes/phing/tasks/system/ExecTaskTest.php, test/etc/tasks/system/ExecTest.xml
I decide to clean up partly the commits in #735
Related to #735 
-
- Added `<env>` nested element to ExecTask.
- Added `resolveexecutable` and `searchpath` attributes to the `<exec>` task.
=> Cleanup of #735 - part 1

classes/phing/tasks/ext/HttpRequestTask.php
See https://github.com/phingofficial/phing/issues/824
=> Fix #824: allow the status-code to be checked in http-request task.

docs/guide/en/source/appendixes/optionaltasks.xml, etc/phing-grammar.rng, test/classes/phing/tasks/ext/HTTP/HttpRequestTaskTest.php, test/etc/tasks/ext/http/httprequest.xml
Added missing requirements for #826 
* fixed/added tests
* added feature to the docs
* added feature to the grammar file
=> Added missing requirements for #826

classes/phing/types/CommandlineMarker.php
Added prefix/suffix support for CommandlineMarker.
=> Cleanup of #735 - part 2

classes/phing/types/CommandlineArgument.php
Fixed static method call and added return type hints.
related to #735
=> Cleanup of #735 - part 4

classes/phing/tasks/ext/TarTask.php
=> Fix for archive task

classes/phing/tasks/ext/phpunit/FormatterElement.php, classes/phing/tasks/ext/phpunit/PHPUnitTask.php, classes/phing/tasks/ext/phpunit/PHPUnitTestRunner7.php, classes/phing/tasks/ext/phpunit/formatter6/CloverPHPUnitResultFormatter6.php, classes/phing/tasks/ext/phpunit/formatter6/Crap4JPHPUnitResultFormatter6.php, classes/phing/tasks/ext/phpunit/formatter6/PHPUnitResultFormatter6.php, classes/phing/tasks/ext/phpunit/formatter6/PlainPHPUnitResultFormatter6.php, classes/phing/tasks/ext/phpunit/formatter6/SummaryPHPUnitResultFormatter6.php, classes/phing/tasks/ext/phpunit/formatter6/XMLPHPUnitResultFormatter6.php, classes/phing/tasks/ext/phpunit/formatter7/CloverPHPUnitResultFormatter7.php, classes/phing/tasks/ext/phpunit/formatter7/Crap4JPHPUnitResultFormatter7.php, classes/phing/tasks/ext/phpunit/formatter7/PHPUnitResultFormatter7.php, classes/phing/tasks/ext/phpunit/formatter7/PlainPHPUnitResultFormatter7.php, classes/phing/tasks/ext/phpunit/formatter7/SummaryPHPUnitResultFormatter7.php, classes/phing/tasks/ext/phpunit/formatter7/XMLPHPUnitResultFormatter7.php, composer.json, composer.lock, test/build.xml, test/classes/phing/tasks/TaskdefTaskTest.php, test/classes/phing/tasks/ext/PHPCPDTaskTest.php, test/classes/phing/tasks/ext/PHPUnitTaskTest.php
=> Added PHPUnit 7 support.

classes/phing/tasks/system/PathConvert.php, classes/phing/types/Path.php, composer.lock, docs/guide/en/source/appendixes/coretasks.xml, etc/phing-grammar.rng, test/classes/phing/tasks/system/PathConvertTest.php
Added `preserveduplicates` to `PathConvert` Task.
=> Added preserve duplicates to PathConvert

classes/phing/tasks/system/ForeachTask.php, composer.lock, docs/guide/en/source/appendixes/coretasks.xml, etc/phing-grammar.rng, test/classes/phing/tasks/system/ForeachTaskTest.php, test/etc/tasks/system/ForeachTaskTest.xml
=> Added index to foreach task

test/classes/phing/tasks/ext/GitTasks/GitArchiveTaskTest.php, test/classes/phing/tasks/ext/GitTasks/GitBaseTest.php, test/classes/phing/tasks/ext/GitTasks/GitBranchTaskTest.php, test/classes/phing/tasks/ext/GitTasks/GitCheckoutTaskTest.php, test/classes/phing/tasks/ext/GitTasks/GitCloneTaskTest.php, test/classes/phing/tasks/ext/GitTasks/GitDescribeTaskTest.php, test/classes/phing/tasks/ext/GitTasks/GitFetchTaskTest.php, test/classes/phing/tasks/ext/GitTasks/GitGcTaskTest.php, test/classes/phing/tasks/ext/GitTasks/GitInitTaskTest.php, test/classes/phing/tasks/ext/GitTasks/GitLogTaskTest.php, test/classes/phing/tasks/ext/GitTasks/GitMergeTaskTest.php, test/classes/phing/tasks/ext/GitTasks/GitPullTaskTest.php, test/classes/phing/tasks/ext/GitTasks/GitPushTaskTest.php, test/classes/phing/tasks/ext/GitTasks/GitTagTaskTest.php
=> Skipped git task tests on windows

classes/phing/Project.php
Reduced white noise in verbose log.
=> No need for verbose log on ref change for UE

classes/phing/system/lang/EventObject.php
=> Added support for object::__toString inside EventObject::__toString

classes/phing/filters/SuffixLines.php
=> Fixed line ending issue in SuffixLines

classes/phing/types/AbstractFileSet.php, test/classes/phing/tasks/ext/VisualizerTaskTest.php, test/classes/phing/types/AbstractFileSetTest.php
=> Added missing precondition checks for references

classes/phing/util/DirectoryScanner.php
=> Reduced duplicate code

classes/phing/types/AbstractFileSet.php
=> Made some args optional.

classes/phing/types/PearPackageFileSet.php
=> Made some more args optional

classes/phing/tasks/ext/phpunit/formatter7/XMLPHPUnitResultFormatter7.php
Related to https://github.com/sebastianbergmann/phpunit/issues/3611
=> Removed PHPUnit\Util\Log\JUnit::setWriteDocument()

classes/phing/tasks/ext/phpunit/JUnit.php, classes/phing/tasks/ext/phpunit/formatter7/XMLPHPUnitResultFormatter7.php
Related to https://github.com/sebastianbergmann/phpunit/issues/3611
=> PHPUnit removed hack

classes/phing/tasks/system/ApplyTask.php
=> [ApplyTask] Fixed wrong condition

classes/phing/tasks/ext/StopwatchTask.php
=> [StopWatch] Fixed visibility of action methods.

classes/phing/IntrospectionHelper.php, classes/phing/tasks/system/PropertyTask.php, classes/phing/types/CommandlineArgument.php
=> IntrospectionHelper should not convert to bool, if a typehinted string was found.

classes/phing/tasks/ext/ExportPropertiesTask.php
Reverts phingofficial/phing#989
=> Revert "Refactor foreach loop into in_array call"

test/classes/phing/PhingTest.php, test/classes/phing/tasks/ext/sonar/SonarConfigurationFileParserTest.php, test/classes/phing/types/PearPackageFileSetTest.php
=> Fixed low deps issue

appveyor.yml
=> Added ext-intl to appveyor.yml

classes/phing/listener/DefaultLogger.php, test/classes/phing/listener/DefaultLoggerTest.php
=> [DefaultLogger] added unit test for buildFinished

appveyor.yml, classes/phing/tasks/system/UpToDateTask.php, composer.lock
=> Fixed indention

classes/phing/tasks/system/PropertyTask.php
=> [PropertyTask] Added type hints

classes/phing/tasks/system/condition/IsTrueCondition.php
Related to #1200 - Closes #1200
=> Fixed IsTrueCondition

test/classes/phing/tasks/system/ConditionTaskTest.php, test/etc/tasks/system/ConditionTest.xml
=> Added regression tests

classes/phing/Project.php
=> [Project] Added inherited properties getter.

classes/phing/PropertyHelper.php
=> [PropertyHelper] Reduced complexity

classes/phing/Task.php
=> [Task] bind task to another task

test/classes/phing/regression/654/FilesetFoldersTest.php
=> [core] Removed not used assignment

test/etc/tasks/system/phing.xml, test/etc/tasks/system/phing/phing.xml, test/etc/tasks/system/phing/references.xml
=> [PhingTask] add xml test files

test/classes/phing/tasks/condition/PhingTaskTest.php
=> [PhingTask] Added test implementations

test/classes/phing/tasks/condition/PhingTaskTest.php
=> [PhingTask] added inherit basedir tests

test/classes/phing/tasks/condition/PhingTaskTest.php
=> [PhingTask] Added ref no inheritance and path test

test/classes/phing/tasks/condition/PhingTaskTest.php
=> [PhingTask] Added override tests

test/classes/phing/tasks/condition/PhingTaskTest.php
=> [PhingTask] Added some more general tests

classes/phing/tasks/system/PhingTask.php
=> [PhingTask] Cleanup code.

classes/phing/tasks/system/ForeachTask.php
=> [ForeachTask] Cleanup code

classes/phing/tasks/system/PhingTask.php, etc/phing-grammar.rng
=> [PhingTask] Added native basedir support.

classes/phing/parser/ProjectConfigurator.php
=> Fixed condition

composer.json, composer.lock
Related to #1385
Caused by https://github.com/guzzle/guzzle/issues/2744
Downgraded Guzzle to 6.5
=> Downgraded guzzle to 6.5

classes/phing/system/io/WindowsFileSystem.php
=> Fixed Windows codepage setting for utf8 beta.

classes/phing/tasks/system/ExecTask.php, test/classes/phing/tasks/system/ExecTaskTest.php, test/etc/tasks/system/ExecTest.xml
Reverts phingofficial/phing#1396
=> Revert "Fix Support for Nested Exec Env Tag - Fixes #1395"

classes/phing/tasks/system/ExecTask.php, test/classes/phing/tasks/system/ExecTaskTest.php, test/etc/tasks/system/ExecTest.xml
* Fixed env handling for windows
* Added test case for windows
=> Fixed env handling for windows

composer.lock, test/classes/phing/tasks/ext/ComposerTaskTest.php, test/etc/tasks/ext/composer/composer.bat, test/etc/tasks/ext/composer/composer.sh
Fixes #1426
Split out testing SetComposer and GetComposer methods. Simulate Composer
existing on the path.
=> ComposerTask tests don't need Composer on the path

.travis.yml
=> [core] Added PHP 8.0 and 8.1 snapshot to travis

classes/phing/system/io/OutputStream.php, classes/phing/tasks/ext/phpunit/formatter7/PHPUnitResultFormatter7.php, test/classes/phing/components/ExtensionPointTest.php, test/classes/phing/regression/ExcludeZipTest.php, test/classes/phing/system/FileOutputStreamTest.php, test/classes/phing/tasks/PropertyTaskTest.php, test/classes/phing/tasks/condition/PhingTaskTest.php, test/classes/phing/tasks/ext/CoverageMergeTest.php, test/classes/phing/tasks/ext/GitTasks/GitBaseTest.php, test/classes/phing/tasks/ext/GitTasks/GitPullTaskTest.php, test/classes/phing/tasks/ext/GrowlNotifyTaskErrorTest.php, test/classes/phing/tasks/ext/PHPUnitTaskTest.php, test/classes/phing/tasks/ext/PhpCSTaskTest.php, test/classes/phing/tasks/ext/WikiPublishTaskTest.php, test/classes/phing/tasks/ext/sonar/SonarTaskTest.php, test/classes/phing/tasks/system/DependSetTest.php, test/classes/phing/tasks/system/PathConvertTest.php, test/classes/phing/tasks/system/XsltTaskTest.php, test/classes/phing/types/MapperTest.php, test/classes/phing/types/TaskdefForCopyTest.php, test/classes/phing/util/DirectoryScannerTest.php, test/classes/phing/util/regexp/PregEngineTest.php
Fixed some risky/warning/... tests.
=> [core] Fixed tests

classes/phing/tasks/ext/phpunit/PHPUnitTestRunner9.php
Added missing process isolation setting for test suite.
=> [PHPUnitTask] Fixed processIsolation setting

classes/phing/tasks/ext/phpunit/PHPUnitTask.php, etc/phing-grammar.rng
Added `haltondefect` to stop test execution by the first defect (error, failure or warning).
```xml
<phpunit haltondefect="true" />
```
=> [PHPUnitTask] Added haltondefect argument

.github/workflows/build.yml
=> Changed build trigger handling

.github/workflows/build.yml
Don't run job if Slack secret isn't available.
=> Only run notify job for phingofficial builds

test/etc/tasks/ext/phploc/build.xml
=> [phploc] Fixed test case.

classes/phing/system/io/BufferedReader.php
=> Fixed line ending issue on windows

composer.lock
Fixed some ns issues in coverage task
=> Updated composer lock

src/Phing/Phing.php
From `phing -help` output:
```
Report bugs to <dev@phing.tigris.org>
```
I'm sure that's not the current way of reporting bugs :)
=> Update report bugs to use issues link

classes/phing/tasks/ext/phpdoc/PhingPhpDocumentorSetup.php, classes/phing/util/FileUtils.php
Reverts phingofficial/phing#1618
=> Revert "Remove the default value before the required parameter."

src/Phing/Io/FileSystem.php
=> [mkdir] Fixed PHP 8 compat

classes/phing/listener/DefaultLogger.php
sorry, rushed. corrected output
@mrook
=> Php 8 1 fix bug

src/Phing/Task/Ext/Smarty/SmartyTask.php
In SmartyTask::setOutputDirectory
=> Fix type of $outputDirectory parameter

src/Phing/Phing.php
Follow-up of https://github.com/phingofficial/phing/commit/a52fe4dd77d253b6756dcb5aee8b2022813dbee3
=> Fix when `sebastian/version` 4+ is installed

src/Phing/Task/System/ReplaceRegexpTask.php, tests/Phing/Test/Task/System/ReplaceRegexpTaskTest.php, tests/etc/tasks/system/ReplaceRegexpTaskTest.xml
Added `flags` attribute to the `ReplaceRegexpTask`
=> [ReplaceRegexpTask] Added `flags` attribute
