phingofficial/phing

classes/phing/tasks/defaults.properties
classes/phing/tasks/system/condition/ConditionBase.php
classes/phing/tasks/system/condition/PhingVersion.php
docs/docbook5/en/source/appendixes/coretasks.xml
test/classes/phing/tasks/condition/PhingVersionTest.php
test/etc/tasks/system/PhingVersionTest.xml

Examples
```
<phingversion property="phingversion"/>
```
Stores the current Phing version in the property phingversion.
```
<phingversion property="phingversion" atleast="2.9"/>
```
Stores the Phing version in the property phingversion if the current Phing version is 2.9.0 or higher. Otherwise the property remains unset.
```
<phingversion property="phing-is-exact" exactly="2.8.2-238-g0cde4a0"/>
```
Sets the property phing-is-exact if Phing 2.8.2-238-g0cde4a0 is running. Neither 2.8.0 nor 2.8.2 would match.
```
<condition property="PhingisOnline">
<and>
<phingversion exactly="2.8.2-238-g0cde4a0"/>
<http url="http://www.phing.info"/>
</and>
</condition>
```
Sets PhingisOnline if Phing 2.8.2-238-g0cde4a0 is running and can get a non-error-response from the Phing homepage.

Added PhingVersion condition / task

---

docs/docbook5/en/source/chapters/gettingstarted.xml
src/Parser/ProjectHandler.php
test/classes/phing/regression/309/Ticket309RegressionTest.php
test/etc/regression/309/basedir-default.xml
test/etc/regression/309/basedir-dot.xml
test/etc/regression/309/sub/basedir-dotdot.xml

See http://www.phing.info/trac/ticket/309
This might be considered a BC break. Acutally it reverts behaviour to what it was many moons ago.
The fix was (IMO) wrong in the first place, improved docs (including docbook) instead.
(cherry-picking eaf81bc316ed965f4d57b66c75a65e5dbf9e0c8c off unstable-3.0)
(This also obsoletes #243)

Make basedir property (including its default value) a path relative to the buildfile

---

docs/docbook5/en/source/appendixes/coretasks.xml
src/Parser/ProjectHandler.php
test/classes/phing/regression/620/Ticket620RegressionTest.php
test/etc/regression/620/importing.xml
test/etc/regression/620/subdir/imported.xml

Here are some tests that cover the changes intended by or at least documented in http://www.phing.info/trac/ticket/620.
The tests are currently *not* passing. In particular, there's still a problem with the various properties that need to be set for the imported buildfile.
This is the output for the current `3.0` version of `phing` (on my machine):
```
~/Projekte/phing/test$ ../bin/phing -f etc/regression/620/importing.xml dump-properties
Buildfile: /Users/mp/Projekte/phing/test/etc/regression/620/importing.xml
importing > dump-properties:
[echo] project.basedir = /Users/mp/Projekte/phing/test/etc/regression/620
[echo] phing.file = /Users/mp/Projekte/phing/test/etc/regression/620/importing.xml
[echo] phing.dir = /Users/mp/Projekte/phing/test/etc/regression/620
[echo] …
```

Add regressions tests for the changes intended by trac-620

---

classes/phing/tasks/system/MatchingTask.php

`AbstractFileSet::addDate` does not exist so it should be `AbstractFileSet::createDate` instead.

Fixed call to createDate in MatchingTask

---

src/Project.php

I think this was intended before, but `$depname = $this->targets[$dep]->getName()` was evaluated before the check. Thus, depending on an unknown target would result in a PHP error rather than a BuildException.

Catch unknown target dependencies with a BuildException. Also make internal methods protected.

---

classes/phing/Phing.php

The system property `user.home` on windows is always empty.

sets the user.home property on windows correctly

---

classes/phing/types/selectors/SelectorUtils.php
docs/docbook5/en/source/appendixes/coretypes.xml
test/classes/phing/regression/724/Ticket724RegressionTest.php
test/classes/phing/types/selectors/SelectorUtilsTest.php
test/etc/regression/724/build.xml

See http://www.phing.info/trac/ticket/724.
This cherry-picks https://github.com/webfactory/phing/commit/e29e738fa17b16cb57c94b213722ccc0022df363 from the unstable-3.0 branch and brings it to `3.0`.

Add a way to include/exclude the base directory of a <fileset>

---

classes/phing/tasks/ext/PhpCodeSnifferTask.php
composer.json
composer.lock

It involves a crude version check, but this maintains compatibility for older versions of PhpCodeSniffer.

Fix PhpCodeSniffer task for version 2.2. (compatible with older versions)

---

test/AbstractBuildFileTest.php

See the docblock for the rationale. If it is not clear enough, I'll add an example here.
This picks a single change out of fb61ebe8960970d591c2943b3d1c1b3656d3cac5.

Add a simple way to run functional tests with buildfiles that contain assertions themselves

---

src/Util/Properties/PropertySet.php
src/Util/Properties/PropertySetImpl.php
test/Util/Properties/PropertySetImplTest.php

This cherry-picks from 616e19b3e17c7d51fba8acbff0ef53211fe33c2c and fb61ebe8960970d591c2943b3d1c1b3656d3cac5.

Add PropertySet::prefix() method to extract properties with a common prefix

---

docs/docbook5/en/source/appendixes/coretypes.xml

Clarification, based on http://ant.apache.org/manual/dirtasks.html and
https://github.com/phingofficial/phing/blob/2221e38ccb8c2ceebd4ee1364ec0a24b3c7fb718/classes/phing/util/DirectoryScanner.php#L312
Cherry-picks 5d966c708990ecb73db801caa667fef51058d390

Document that in a FileSet include/exclude "foo/" means "foo/**"

---

classes/phing/system/io/Win32FileSystem.php

Just to have the same result behavior as for the `UnixFileSytem::compare()`

Removed type cast to boolean.

---

classes/phing/tasks/ext/phpmd/PHPMDFormatterElement.php

It's PMD instead PPMD ;-). Fix: [PHP Error] include_once(PHP/PPMD/Renderer/XMLRenderer.php): failed to open stream: No such file or directory.

Fix: "Fatal error: Class 'PHP_PMD_RENDERER_XMLRenderer' not found"

---

classes/phing/tasks/ext/FileHashTask.php
docs/docbook5/en/source/appendixes/optionaltasks.xml
test/classes/phing/tasks/ext/FileHashTaskTest.php
test/etc/tasks/ext/filehash.xml

Added optional algorithm attribute to support more hashtypes.
Example:
```
<filehash file="filehash.bin" propertyName="filehash.crc32" algorithm="crc32"/>
<echo>${filehash.crc32}</echo>
```

Added optional algorithm attribute to FileHashTask

---

bin/pear-phing
bin/phing
bin/phing.php
build/phing-stub.php

I've removed `-logger` in `bin/pear-phing` and `bin/phing` and add it in a common and unique entry `bin/phing.php` which is called by all sources (including `bin/pear-phing.bat` and `bin/phing.bat`).
The default is then `phing.listener.AnsiColorLogger` is color is supported and if no `-logger` provided.

Solve ticket #1134 and add color support for all platforms

---

classes/phing/tasks/ext/phpmd/PHPMDTask.php

This was happening silently and causing phing to crash when phpmd is installed via composer.

Fixed "Cannot redeclare class PHP_PMD_RuleSetFactory" in the phpmd task.

---

classes/phing/Phing.php
classes/phing/Project.php

Added ant like keep-going mode
```
$ phing [-k|-keep-going]
```

Added keep going mode

---

test/classes/phing/tasks/ext/SymlinkTaskTest.php

The automatic execution of tearDown causes an exception on windows.

Fixed SymlinkTaskTest execution under windows

---

classes/phing/tasks/system/ImportTask.php
docs/docbook5/en/source/appendixes/coretasks.xml
test/classes/phing/tasks/ImportTaskTest.php
test/etc/tasks/importing-multi.xml
test/etc/tasks/imports/imported-multi-1.xml
test/etc/tasks/imports/imported-multi-2.xml

**Use case**
I pull down alot of different build.xml files with composer. I don't want to have to add multiple import references, especially if I am adding a new library.
Giving Phing and almost "autoload" kind of functionality.
**Solution**
Create a ImportMultiTask object for this case.
```
<import-multi files="vendor/previousnext/*/build*.xml" optional="true" />
```
**Help**
Can I please get some guidance on:
* If this could be committed to Phing.
* How I can get it over the line so I can be committed.

Adds ImportMultiTask.

---

classes/phing/tasks/ext/UntarTask.php

This is a fix for [Issue #1208: When UntarTask fails to extract an archive it should tell why](https://www.phing.info/trac/ticket/1208).

Fixes #1208 - Inform the user why an archive could not be extracted.

---

classes/phing/tasks/ext/phpunit/FormatterElement.php
classes/phing/tasks/ext/phpunit/formatter/Crap4jPHPUnitResultFormatter.php

PHPUnit has build in the Crap4j-Report for over a year now.
Its really easy to bring it to phing.
Example:
```xml
<phpunit codecoverage="true">
<formatter type="xml" todir="reports" />
<formatter type="plain" todir="reports" />
<formatter type="clover" todir="reports" />
<formatter type="crap4j" todir="reports" />
<batchtest>
<fileset dir="tests">
<include name="**/*Test*.php"/>
</fileset>
</batchtest>
</phpunit> 
```

Added Crap4jPHPUnitResultFormatter

---

docs/docbook5/en/source/appendixes/optionaltasks.xml
docs/docbook5/en/source/chapters/settingup.xml

This is the required documentation for the new SSL attribute added to the FtpDeployTask in https://github.com/phingofficial/phing/pull/352/ which was implemented by @patrickdreyer 
I've added a row describing the new SSL attribute to the section for FtpDeploy and also added Net_FTP as an optional dependency in the "Setting Up Phing" chapter.

Document new SSL attribute for FtpDeploy (#PR352).

---

classes/phing/system/io/YamlFileParser.php
test/classes/phing/system/io/YamlFileParserTest.php

Looks like the most recent modification to the Yaml feature introduced a bug. This should fix it. Also need to see why regression test did not catch this.

Fixing bug in Yaml file parser.

---

classes/phing/tasks/defaults.properties
classes/phing/tasks/ext/NotifySendTask.php
docs/docbook5/en/source/appendixes/optionaltasks.xml
test/build.xml
test/classes/phing/tasks/ext/NotifySendTaskTest.php
test/etc/tasks/ext/NotifySendTaskTest.xml

This will enable phing to send desktop notifications via notify-send.
The code for this was sitting in my separate repo ( https://github.com/kenguest/Phing-NotifySendTask ), but I've added extra logging, unit tests, and documentation.

Integrate new NotifySendTask

---

classes/phing/tasks/ext/PhpCodeSnifferTask.php
docs/docbook5/en/source/appendixes/optionaltasks.xml
test/classes/phing/tasks/ext/PhpCodeSnifferTaskTest.php
test/etc/tasks/ext/phpcs/build.xml

We had a case in the past where a sniff failed to run in our setup.  By having the sniffs in a property we would be able to validate that the sniffs were in fact used.

Add propertyName to PhpCodeSniffer

---

classes/phing/tasks/ext/phpdoc/PhingPhpDocumentorErrorTracker.php

I accidental ran into this while checking my own codebase.

Fix doc block, type hint will not be used

---

classes/phing/tasks/ext/FileSyncTask.php

I've faced with tiny issue, that should be fixed 
`PHP Notice:  Undefined property: FileSyncTask::$options in /www/phing/classes/phing/tasks/ext/FileSyncTask.php on line 264`

Missed property has been added back to class definition

---

classes/phing/tasks/ext/TarTask.php

Improving compatibility with modern PHP versions 
Here fix for:
`PHP Deprecated:  Non-static method PEAR::isError() should not be called statically, assuming $this from incompatible context in /www/phing/classes/phing/tasks/ext/TarTask.php on line 247`

Static method call replaced in favor of dynamic 

---

docs/docbook5/en/source/appendixes/coretasks.xml
docs/docbook5/en/source/appendixes/coretypes.xml
docs/docbook5/en/source/appendixes/optionaltasks.xml
docs/docbook5/en/source/chapters/about.xml
docs/docbook5/en/source/chapters/gettingstarted.xml
docs/docbook5/en/source/chapters/projcomponents.xml
docs/docbook5/en/source/chapters/settingup.xml

I also adjusted some programlisting example content so the PDF version of the manual will render better - as some of the examples were too long to fit and because of that were truncated.

Fix typos, some markup and update some portions of documentation regarding cli flags/parameters.

---

classes/phing/tasks/ext/phpunit/PHPUnitTask.php

I have code where I don't use autoloads. I cannot run the unit tests for this currently because I get the following error:
```
[zippy1981@basement test]$ ../bin/phing
Buildfile: /home/zippy1981/src/phing/test/build.xml
Phing Build Tests > initialize:
Phing Build Tests > configure:
[echo] -------------------------------------------------
[echo]  +++++ Running Phing  unit tests
[echo] -------------------------------------------------
Phing Build Tests > reports:
[delete] Deleting directory /home/zippy1981/src/phing/test/tmp
[mkdir] Created dir: /home/zippy1981/src/phing/test/tmp
PHP Fatal error:  Call to undefined method PHPUnit_Util_Configuration::getSeleniumBrowserConfiguration() in /home/zippy1981/src/phing/classes/phing/tasks/ext/phpunit/PHPUnitTask.php on line 390
[zippy1981@basement …
```

Deal with cases where autoload isn't used

---

classes/phing/tasks/ext/phpunit/PHPUnitTask.php

The Mac operating system can be set up with a filesystem that uses case-insensitive file names (specifically, the `Mac OS Extended (Journaled)` filesystem). Under this filesystem, `PHPUnit/Runner/Version.php`, and `phpunit/Runner/Version.php` refer to the same file. However, PHP does not recognize that this file has already been included, and attempts to include it again.
Here is the error that occurs (when the `@` operator is removed from `PHPUnitTask` [here](https://github.com/phingofficial/phing/blob/master/classes/phing/tasks/ext/phpunit/PHPUnitTask.php#L88)). Note that this is a fatal error that does not produce a `E_RECOVERABLE_ERROR`. As such, this task is unusable in this type of filesystem:
```
PHP Fatal error:  Cannot redeclare class PHPUnit_Runner_Version in …
```

Handle case where Linux-based OS is using a case-insensitive filesystem

---

classes/phing/BuildException.php
classes/phing/ExitStatusException.php
classes/phing/Phing.php
classes/phing/tasks/system/FailTask.php
classes/phing/tasks/system/condition/NestedCondition.php
docs/docbook5/en/source/appendixes/coretasks.xml

Extends phing with status code on shutdown and updated FailTask to support status flag and nested condition.
Example:
```
<fail status="255">
<condition>
<not>
<isset property="thisdoesnotexist"/>
</not>
</condition>
</fail>
```

Added support for status code on exit and updated FailTask.

---

classes/phing/mappers/CutDirsMapper.php
classes/phing/types/Mapper.php
docs/docbook5/en/source/appendixes/coremappers.xml
test/classes/phing/types/MapperTest.php
test/etc/types/mapper.xml

Added ant like `CutDirsMapper`.
Example:
```
<property name="input" value="${php.tmpdir}/testinput"/>
<property name="output" value="${php.tmpdir}/testoutput"/>
<mkdir dir="${input}/a/b/c"/>
<touch file="${input}/a/b/D"/>
<touch file="${input}/a/b/c/E"/>
<copy todir="${output}">
<mapper type="cutdirs" to="2"/>
<fileset dir="${input}"/>
</copy>
```
Would result in:
```
[copy] Copying 2 files to C:\Users\xxx\AppData\Local\Temp\testoutput
[copy] From C:\Users\xxx\AppData\Local\Temp\testinput\a\b\c\E to C:\Users\xxx\AppData\Local\Temp\testoutput\c\E
[copy] From C:\Users\xxx\AppData\Local\Temp\testinput\a\b\D to C:\Users\xxx\AppData\Local\Temp\testoutput\D
```
Documentation and tests are on the way ;)

Added CutDirsMapper

---

.gitattributes

The Docs folder, once downloaded is 5.64 MB, which is large when it is not a necessity

Export ignore docs file

---

classes/phing/system/io/IniFileParser.php
composer.json
composer.lock
test/classes/phing/system/io/IniFileParserTest.php
test/phpunit.xml

Fix handling of line breaks on Windows in property files.
```
someproperty = test,\\
test1,\\
test2
```
Didn't work when EOL is `\r\n`

Fix handling of line breaks on Windows in property files

---

classes/phing/tasks/ext/FileSyncTask.php
docs/docbook5/en/source/appendixes/optionaltasks.xml

Use comma separated values to exclude multiple files/directories.
e.g.: exclude="a,b" will produce command lineoptions --exclude="a" --exclude="b"`

Exclude multiple files/directories

---

classes/phing/listener/MailLogger.php
docs/docbook5/en/source/appendixes/coreloggers.xml

Added more properties to MailLogger:
- phing.mail.log.failure.notify [default: true] - Send build failure e-mails?
- phing.mail.log.success.notify [default: true] - Send build success e-mails?
- phing.mail.log.failure.to [required if failure mail to be sent] - Address to send failure messages to
- phing.mail.log.success.to [required if success mail to be sent] - Address to send success messages to
- phing.mail.log.failure.cc [no default] - Address to send failure messages to carbon copy (cc)
- phing.mail.log.success.to [no default] - Address to send success messages to carbon copy (cc)
- phing.mail.log.failure.bcc [no default] - Address to send failure messages to blind carbon copy (bcc)
- phing.mail.log.success.bcc [no default] - Address to send success messages to blind carbon copy …

Added more function to MailLogger.

---

classes/phing/system/io/Win32FileSystem.php

I got an error on run phing.
```
> phing prepare
Notice: iconv(): Wrong charset, conversion from `UTF-8' to `Windows-932//IGNORE' is not allowed in vendor\phing\phing\classes\phing\system\io\Win32FileSystem.php on line 635
Buildfile:  does not exist!
```
Now, phing use `iconv` or `mb_convert_encoding` for fixing windows encoding.
However, `Windows-${codepage}` is not usual codepage encoding format.
My `cmd.exe` use codepage 932.
`CP932` exists in supported encoding for `iconv` and `mbstring`, but `Windows-932` is not.
So, `fixEncoding` function failed and returned not string...
I request to use `CP` for encoding prefix.
Thanks!
* https://www.gnu.org/software/libiconv/
* http://php.net/manual/ja/mbstring.supported-encodings.php

Fix Windows encoding convertion

---

classes/phing/tasks/ext/dbdeploy/DbDeployTask.php

Adding a warning if user includes --// in a DB delta as it will likely cause a schema migration to fail and this is a common issue due to a popular tutorial using '--//' instead of '-- //' for comments

DBDeploy script update to address an issue that arises when following a popular tutorial

---

classes/phing/tasks/ext/hg/HgUpdateTask.php

The branch property for the hgupdate task was being ignored. This pull request fixes that bug.

Fix bug with hgupdate branch being ignored.

---

docs/docbook5/en/source/appendixes/factsheet.xml
docs/docbook5/en/source/chapters/extending.xml
docs/docbook5/en/source/chapters/settingup.xml

https://www.phing.info/trac/ticket/1259 - all references to PHP_CLASSPATH as an environment variable have now been removed.

[#1259] Remove reference to PHP_CLASSPATH as an environment variable.

---

classes/phing/UnknownElement.php

When executing the test build file with ProfileLogger enabled, it comes to an exception:
```
resolvepath: finished Sun, 04 Sep 2016 21:34:34 +0000 (0.0307 seconds)
path: started Sun, 04 Sep 2016 21:34:34 +0000
Fatal error: Uncaught Error: Call to undefined method Path::getTaskName() in xxx\classes\phing\UnknownElement.php on line 251
Error: Call to undefined method Path::getTaskName() in xxx\classes\phing\UnknownElement.php on line 251
```
Contribution would fix this behavior.

Fixed getTaskName bug

---

classes/phing/tasks/ext/SassTask.php

This is a fix for issue 1262 (ref. https://www.phing.info/trac/ticket/1262)
When using the new SassTask with the default settings and having the scssphp package installed, but not the sass ruby gem, I'm getting the following fatal error:
```
PHP Fatal error:  Uncaught Error: Call to a member function compile() on null in /home/pieter/v/joinup/vendor/phing/phing/classes/phing/tasks/ext/SassTask.php:1105
Stack trace:
#0 /home/pieter/v/joinup/vendor/phing/phing/classes/phing/tasks/ext/SassTask.php(1016): SassTask->compile('/home/pieter/v/...', '/home/pieter/v/...', true)
#1 /home/pieter/v/joinup/vendor/phing/phing/classes/phing/tasks/ext/SassTask.php(976): SassTask->processFile(true)
#2 /home/pieter/v/joinup/vendor/phing/phing/classes/phing/UnknownElement.php(100): SassTask->main()
#3 …
```

Fix fatal error in SassTask when scssphp is installed but the sass gem is not

---

classes/phing/tasks/ext/SassTask.php

The new SassTask is not compatible with PHP 7. Interestingly, earlier on in the development of the PR it was compatible, but at some point backwards compatibility with PHP 5.2 was added but this broke PHP 7.
This error occurs when trying to use the SassTask with scssphp on PHP 7:
> call_user_func_array() expects parameter 1 to be a valid callback, non-static method Leafo\ScssPhp\Compiler::__construct() cannot be called statically [line 1219 of /home/pieter/v/joinup/vendor/phing/phing/classes/phing/tasks/ext/SassTask.php]

Make SassTask compatible with PHP 7

---

classes/phing/Phing.php

When using directly the phar without composer autoload with the -propertyfile option, I was having a FATAL ERROR
$ php phing.phar -propertyfile config.ini help 
PHP Fatal error:  Class 'FileParserFactory' not found in phar:///home/workspace/phing.phar/classes/phing/Phing.php on line 515
It seems that in PR #488 , the include for class FileParserFactory was missing

Fix missing include to FileParserFactory 

---

classes/phing/listener/XmlLogger.php

Add an `xml-stylesheet` tag if property `phing.XmlLogger.stylesheet.uri` was set.

Added optional use of an stylesheet [XmlLogger]

---

classes/phing/parser/ProjectConfigurator.php

Allows to set properties to null. Needed when from the programmatic point of view "" != null
Please test and review if it makes sense. I'm not sure if the null value test was not intentional - but for me it was a bug as it reported null-set property as undefined => it won't replace it.

Test if property was set, instead of testing for non-null value

---

classes/phing/tasks/ext/PearPackage2Task.php
classes/phing/tasks/ext/PearPackageTask.php
classes/phing/util/PearPackageScanner.php

Corrects the "Non-static method PEAR::isError() should not be called statically"
Same fix as this one: https://www.phing.info/trac/ticket/460
This is the same pull request as #464 but with rebase.

PHP 5.x compatibility with Pear::isError

---

classes/phing/tasks/system/PropertyTask.php

In case of a referenced `Path` object, PropertyTask tries to stringify the `Path` object by calling toString method, which is not available.

Fixed referenced objects for PropertyTask

---

classes/phing/filters/StripPhpComments.php
test/etc/filters/expected/stripphpcomments.test
test/etc/filters/input/stripphpcomments.test

StripPhpComments with token scan instead of regex

---

classes/phing/types/Path.php

Related to #546 to support the combination of `PathConvert` with `FileSet` and `Path`:
```
<fileset dir="${basedir}" id="src.files"/>
<pathconvert pathsep="," property="files" refid="src.files"/>
<echo>${files}</echo>
```
Property `files` can now be used as a set of files separated by colons to be used inside an `<arg>` element inside an `ExecTask`

Added FileSet support to Path

---

classes/phing/listener/DefaultLogger.php

Rounding error results in DefaultLogger::formatTime(90) => "2 minutes 30.00 seconds" but should be "1 minute 30.00 seconds" instead.

Fix formated time

---

classes/phing/tasks/defaults.properties
classes/phing/tasks/system/TruncateTask.php
docs/docbook5/en/source/appendixes/coretasks.xml
etc/phing-grammar.rng
test/classes/phing/tasks/system/TruncateTaskTest.php
test/etc/tasks/system/TruncateTaskTest.xml

Example:
```
<truncate file="foo" />
```
Sets the length of file `foo` to zero.

Added Truncate Task

---

classes/phing/Phing.php
classes/phing/Project.php
classes/phing/parser/ProjectHandler.php
docs/docbook5/en/source/appendixes/projcomponents.xml
docs/docbook5/en/source/chapters/gettingstarted.xml

Phing build would support a 'Strict' mode, which indicates to consider a warning as an error and raises a buildException to abort the build process.
**Ticket**
http://www.phing.info/trac/ticket/918
**Specs**
Phing build would support a 'Strict' mode, with the default value as Off (to enable backward compatibility until complete future migration). The 'strict' mode, when enabled, considers all the warnings (which are raised with "MSG_WARN" level) as an error, and raises a buildException to abort the build process.
This pull request adds the following functionalities:
1) The Project tag supports new attribute - strict (boolean), indicating the build process mode.
2) The Phing command-line utility would support two new parameters:
-strict runs build in strict mode, considering a warning as …

Phing Strict Build Mode

---

classes/phing/BuildEvent.php
classes/phing/parser/ProjectConfigurator.php

Minor mistype/swap of characters. Became aware of in one's of our own
projects in which phing was used so caught these as by-catch.
Via command line:
find . -type f -name '*.php' -exec grep -q execption {} \; \
-exec sed -i 's/execption/exception/g' {} \; -print
./classes/phing/BuildEvent.php
./classes/phing/parser/ProjectConfigurator.php

Typo change execption to exception

---

build/build.xml
build/manifest.xml

Fixes #633 
What will be needed during release:
- gpg key generated for `mrook@php.net`
- files that will be signed:
- phing-*.phar
- phing-*.tgz
- phing-*.zip
- public key should be published on `hkps.pool.sks-keyservers.net`
Files that should be uploaded to GitHub releases:
- phing-*.phar
- phing-*.phar.asc
- phing-*.phar.sha1
- phing-*.phar.sha256
- phing-*.phar.sha384
- phing-*.phar.sha512 
More info: https://phar.io/howto/sign-and-upload-to-github.html

#633 - phive integration

---

classes/phing/contrib/DocBlox/Parallel/Manager.php

When the pcntl extension isn\'t installed, then the DocBlox_Parallel_Manager doesn't create the pipe property. In stopExecution() the Manager tries to call the push method on an undefined propety.
I have added a simple isset before the call.

Fatal Error when pcntl extension isn't installed

---

classes/phing/types/AbstractFileSet.php

Related to #649 :
Fixed error message to display the right type implementation.

Fixed error message in `AbstractFileSet` Related to #649

---

classes/phing/tasks/ext/JsHintTask.php

issues/errors included in jslint styled reports are on "<issue>" XML elements not "<error>" elements and so were being skipped over.
This PR fixes that problem.

Output of jslint report wasn't being parsed correctly by jshint.

---

classes/phing/ProjectComponent.php

Related to #649 :
`ProjectComponent` should hold an instance of `Location`.

Preinstantiating location in constructor. Related to #649

---

classes/phing/util/FileUtils.php
test/classes/phing/tasks/condition/FilesMatchTest.php
test/etc/tasks/system/FilesMatchTest.xml

Check if one of the files is a dir before file_get_contents

file_get_contents in windows return a permission error if the file is  a dir

---

docs/docbook5/en/source/chapters/projcomponents.xml

Fix example code for the conditions »ispropertytrue« and »ispropertyfalse«
by replacing the wrong attribute »name« with the correct »property«.

[BUGFIX] Documentation: Fix condition examples

---

classes/phing/contrib/DocBlox/Parallel/Manager.php

Its not enough to check for `isset($worker->pipe)` on property. This fixes Call to a member function push() on null in ... Manager.php:237 #706

Fix invalid usage of isset on a property in parallel task

---

classes/phing/tasks/system/ConditionTask.php

Fixes the correct task name for conditions.

Added missing constructor call.

---

classes/phing/tasks/ext/TarTask.php
docs/docbook5/en/source/appendixes/optionaltasks.xml
etc/phing-grammar.rng

Since TarTask is based on "pear/Archive_Tar" and the latter is capable of creating lzma2-compressed archives I've exposed an option to create such archives.

Added LZMA2 algorithm support for TarTask

---

classes/phing/tasks/ext/NotifySendTask.php
test/classes/phing/tasks/ext/NotifySendTaskTest.php

* Amend for PSR2 Coding Style.
* Use StringHelper::booleanValue instead of blindly casting to boolean value (re Silent attribute).
* Use new FileSystem which method to determine if executable is available.
* Extend debug logging messages.

Additional work done to NotifySend task.

---

docs/docbook5/en/source/appendixes/optionaltasks.xml
docs/docbook5/en/source/chapters/extending.xml
docs/docbook5/en/source/chapters/introduction.xml

...rather than having people code their own "yes|y|no|n|true|t|1|0" to boolean conversion code...

Demonstrate StringHelper::booleanValue in the custom MyEchoTask code.

---

classes/phing/Phing.php
test/classes/phing/PhingTest.php

The php.ini can contain values like: '1K' (as 1 kilobyte) instead of '1024' or '1M' as (1 megabyte) instead of '1048576'.
For example:
memory_limit = 32M
post_max_size = 32M
Phing is buggy as '1M' is handled as same as '1K'.
Additionally $val = '2k' * 1024 cause a "Notice: A non well formed numeric value encountered".
Before PHP 7 it was ignored and handled as 2 * 1024.

Fix: php.ini variable evaluation and "Notice: A non well formed numeric value encountered"

---

docs/docbook5/en/source/appendixes/optionaltasks.xml

This new example shows how you can use SQL directly into your buildfile. 
The query uses the `${color}` property, once executed the result is saved on xml format.
```sql
<property name="color" value="orange"/>
<pdosqlexec url="mysql:host=localhost;dbname=test"
userid="username" password="password">
<transaction>
SELECT * FROM products WHERE color = '${color}';
</transaction>
<formatter type="xml" outfile="path/to/output.xml"/>
</pdosqlexec>
```

Add new example for PdoSqlTask

---

docs/docbook5/en/source/chapters/projcomponents.xml

Since `available` condition has no examples I wrote one:
```sql
<if>
<available file="README.md"/>
<then>
<echo message="Please read README.md"/>
</then>
</if>
```
In this example I check the availability of `README.md` file to echo a message.
I deliberately omitted the `property` and `value` attributes which are mandatory for `AvailableTask` but are ignored by `available` condition.

Add new example for Available condition

---

classes/phing/tasks/system/PathConvert.php

Added missing `Path::addFilelist()` when used as reference.

Fixed usage of filelist if PathConvert uses a reference.

---

classes/phing/tasks/ext/HttpGetTask.php

Added missing exception argument to the log method.
Related to #760

Fixed log method - HttpGetTask.

---

docs/docbook5/en/source/appendixes/factsheet.xml

It seems `phing.startTime` built-in property [exists since 2008](https://www.phing.info/trac/ticket/255).
I think this property can be useful for others, therefor I added it to documentation.

Doc: add phing.startTime built-in property

---

classes/phing/filters/LineContains.php
docs/docbook5/en/source/appendixes/corefilters.xml
etc/phing-grammar.rng
test/classes/phing/filters/LineContainsTest.php
test/etc/filters/expected/linecontains-negate.test
test/etc/filters/linecontains.xml

Example getting all non-matching lines:
```xml
<filterreader classname="phing.filters.LineContains">
<param type="contains" value="beta"/>
<param type="negate" value="true"/>
</filterreader>
```

Added negate attribute to the `linecontains` filter.

---

classes/phing/tasks/system/PhingTask.php

Be more strict on adding an empty string as target name.

Target attrib of PhingTask must not be empty.

---

classes/phing/types/Reference.php

Just as a peparation for sub-projects.

Added public setter/getter to reference object.

---

etc/phing-grammar.rng

We can choose between `output` and `destdir` attributes.

Fixed grammar for phpdoc2 task.

---

classes/phing/Phing.php

Multiple property file includes by `-propertyfile` options
```bash
$ phing -propertyfile a.properties -propertyfile b.properties
```

Added multiple property file inclusion.

---

Vagrantfile

Added
```
ansible.extra_vars = {
ansible_python_interpreter: "/usr/bin/python3"
}
```
to the `Vagrantfile` - related to #712

Fixed #712

---

classes/phing/tasks/ext/phar/PharPackageTask.php
test/classes/phing/regression/ExcludeZipTest.php
test/classes/phing/tasks/ext/DbDeployTaskTest.php
test/classes/phing/tasks/ext/HgTasks/HgCloneTaskTest.php
test/classes/phing/tasks/ext/HgTasks/HgInitTaskTest.php
test/classes/phing/tasks/ext/HgTasks/HgPullTaskTest.php
test/classes/phing/tasks/ext/HgTasks/HgPushTaskTest.php
test/classes/phing/tasks/ext/HgTasks/HgRevertTaskTest.php
test/classes/phing/tasks/ext/HgTasks/HgTagTaskTest.php
test/classes/phing/tasks/ext/HgTasks/HgTaskTestSkip.php
test/classes/phing/tasks/ext/HgTasks/HgTaskTestSkipper.php
test/classes/phing/tasks/ext/HgTasks/HgUpdateTaskTest.php
test/classes/phing/tasks/ext/PharDataTaskTest.php
test/classes/phing/tasks/ext/PharPackageTaskTest.php
test/classes/phing/tasks/ext/ZipUnzipTaskTest.php
test/classes/phing/tasks/ext/svn/SvnCheckoutTaskTest.php
test/classes/phing/tasks/ext/svn/SvnExportTaskTest.php
test/classes/phing/tasks/ext/svn/SvnInfoTaskTest.php
test/classes/phing/tasks/ext/svn/SvnLastRevisionTaskTest.php
test/classes/phing/tasks/ext/svn/SvnListTaskTest.php
test/classes/phing/tasks/ext/svn/SvnLogTaskTest.php
test/classes/phing/tasks/ext/svn/SvnPropTaskTest.php
test/classes/phing/tasks/ext/svn/SvnSwitchTaskTest.php
test/classes/phing/tasks/ext/svn/SvnTaskTestSkip.php
test/classes/phing/tasks/ext/svn/SvnUpdateTaskTest.php
test/classes/phing/types/PearPackageFileSetBuildTest.php
test/classes/phing/types/PearPackageFileSetTest.php
test/classes/phing/util/PearPackageScannerTest.php

This PR adds skips to tests that depends on external utilities when that utilities are absent/disabled. Thanks to this, tester does not have to install unnecessary utilities.

Skip tests

---

classes/phing/filters/LineContains.php
classes/phing/filters/LineContainsRegexp.php
classes/phing/filters/ReplaceTokens.php
classes/phing/filters/StripLineComments.php

Fixed some typos in error messages. Should be `Expected` instead of `Excpected`.

fixed typos in error messages

---

docs/guide/en/source/appendixes/coretasks.xml

Makes no sense inside a build script. The `fallback` setter needs a `Project` instance and not a string though.

Removed `fallback` part of the `PropertyTask` documentation

---

classes/phing/util/StringHelper.php

Values like `'0000'` are taken as boolean, which is not the desired result.

Fixed isBoolean check.

---

classes/phing/tasks/ext/PhpCodeSnifferTask.php

Fix error of PHP_CodeSniffer_Reports_PhingRemoveFromCache try to write to content to directory path :
[PHP Error] file_put_contents(/data/): failed to open stream: Is a directory [line 191 of /data/library/vendor/squizlabs/php_codesniffer/CodeSniffer/Reporting.php]

Fix PHP CodeSniffer cache write to directory

---

.travis.yml

Travis supports to use the latest snapshot versions for php versions, so we should use them.

Added snapshot versions for all sup. php versions

---

classes/phing/filters/XsltFilter.php

Fixed the XsltFilter to react correctly on failure.
This solves the test execution, but shows us another failure.
see https://travis-ci.org/phingofficial/phing/jobs/393323312
```
[filehash] Calculating sha1 hash from: /home/travis/build/phingofficial/phing/build/full/phing-3.0.0-alpha2.phar
[exec] gpg: skipped "mrook@php.net": secret key not available
[exec] gpg: signing failed: secret key not available
[phingcall] Task exited with code 2
BUILD FAILED
/home/travis/build/phingofficial/phing/build/build.xml:203:26 Execution of the target buildfile failed. Aborting.
```

Fixed test execution.

---

classes/phing/util/DirectoryScanner.php

As mentioned on our slack channel by @jawira there is a problem extending the default excludes list. @jawira would you mind to verify this?

Fixed DefaultExcludes by removing an old hhvm fix

---

classes/phing/util/DirectoryScanner.php

Added methods getting the count of included dirs or files inside a directoryscanner. Made the getter of included files or dirs sorted.

Cleanup of #735 - part 3

---

classes/phing/PropertyHelper.php
docs/guide/en/source/chapters/gettingstarted.xml
docs/guide/en/source/master.xml
test/classes/phing/tasks/PropertyTaskTest.php
test/etc/tasks/property.xml

Instead of a property value we would be able to invoke the `__toString` method of a reference like:
```
<fileset id="sourcefiles" dir="src" includes="**/*.php"/>
<echo> sourcefiles = ${toString:sourcefiles} </echo>
```

Expanding a Property Reference with ${toString:}

---

classes/phing/tasks/ext/git/GitLogTask.php
test/classes/phing/tasks/ext/GitTasks/GitLogTaskTest.php

Fix issue with string coming back from executing the git log command not being trimmed.

#946: Trim outputProperty value of GitLogTask.

---

classes/phing/tasks/ext/VersionTask.php
docs/guide/en/source/appendixes/optionaltasks.xml
test/classes/phing/tasks/ext/VersionTaskTest.php

I modified VersionTask to be able to manage 'v' prefix in version numbers. I also updated the doc and added tests for \VersionTask::getVersion.
I deleted \VersionTask::checkStartingVersion since the regex I added implicitly checks the validity of version too.

VersionTask can manage 'v' prefix

---

test/classes/phing/BuildFileTest.php

If there is no previous exception inside a failing test, there would be a null pointer exception then.

Fixed null pointer exception

---

classes/phing/tasks/ext/VersionTask.php

Using VersionTask is not so obvious at the beginning, so I added some log messages. I also did a small code refactoring.

Add verbosity to VersionTask

---

classes/phing/UnknownElement.php

Explicitly passing NULL to get_class triggers E_WARNING as of PHP 7.2[1].
[1] https://secure.php.net/get_class

Avoid calling get_class on null in UnknownElement.

---

docs/guide/en/source/appendixes/optionaltasks.xml

Small typo in `PropertyCopy` documentation

Fix PropertyCopy documentation

---

classes/phing/listener/DefaultLogger.php

If in verbose mode or a not `BuildException` exception is thrown there is no error message available in the `DefaultLogger` output.

Added exception message to verbose output.

---

classes/phing/tasks/ext/StopwatchTask.php

Get rid of methods using the `DispatchTask`

StopwatchTask should use DispatchTask

---

classes/phing/util/FileUtils.php

The third parameter of \FileUtils::createTempFile should be optional, otherwise the default value (three lines below method's signature) will never be used.
```
$parent = ($parentDir === null) ? sys_get_temp_dir() : $parentDir->getPath();
```

Third $parentDir param should be optional

---

classes/phing/tasks/ext/ioncube/IoncubeEncoderTask.php
docs/guide/en/source/appendixes/optionaltasks.xml

Every new php version we come to the problem that the phing task have to manually changed to support the new version. See #335 #485 #130 
To solve this once and for all the phpversion should be removed and allow everything given. So we can also finally use this x64 versions of ioncube encoder without renaming the encoder files.

 Opened IoncubeEncoderTask to all php versions

---

classes/phing/tasks/ext/coverage/CoverageReportTask.php

create_function is deprecated in 7.2, but, anonymous functions have been supported since 5.3, so including this update in version 3 (which requires 7.1+) should be harmless.
(I submitted this earlier, but, the commits got ugly and screwed up)

Replaced deprecated create_function calls with anonymous functions.

---

test/phpunit.xml

It is not possible to execute unit tests with codecoverage of a single phpunit file.
Example: running `PhingTest` as phpunit test under phpstorm wich will execute:
```
php.exe -dxdebug.coverage_enable=1 C:\XXX\phing/vendor/phpunit/phpunit/phpunit --coverage-clover C:\XXX\.PhpStorm2018.3\system\coverage\phingPhpArrayRebase$PhingTest.xml --configuration C:\XXX\phing\test\phpunit.xml PhingTest C:\XXX\phing\test\classes\phing\PhingTest.php --teamcity
```
will end with:
```
PHPUnit 7.5.3 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.1.8 with Xdebug 2.5.5
Configuration: C:\XXX\phing\test\phpunit.xml
Warning - The configuration file did not pass validation!
The following problems have been detected:
Line 13:
- Element 'phpunit', attribute 'syntaxCheck': The attribute 'syntaxCheck' …
```

Fixed single test execution of phpunit tests.

---

classes/phing/tasks/ext/FtpDeployTask.php
classes/phing/tasks/ext/pearpackage/PEARPackageFileManagerFileset.php

each() is deprecated in PHP 7.2

Replaced while...each loops with foreach.

---

classes/phing/util/DirectoryScanner.php

Non static methods should not be called statical.
Related to #1034

Fixed DirectoryScanner - wrong method call

---

classes/phing/tasks/system/condition/HttpCondition.php

Fixed deprecated issue on php 7.3 for the HttpCondition.
Related to #1084

[HttpCondition] Removed deprecated constant php 7.3 compat

---

classes/phing/tasks/system/ExecTask.php
classes/phing/tasks/system/element/LogLevelAware.php

Uses LogLevelAware trait to avoid duplicated code.

Reduced code

---

classes/phing/tasks/ext/phpstan/CommandBuilder/PHPStanAnalyseCommandBuilder.php
test/classes/phing/tasks/ext/PHPStanTask/Acceptance/PHPStanTaskTest.php
test/classes/phing/tasks/ext/PHPStanTask/Unit/CommandBuilder/PHPStanAnalyseCommandBuilderTest.php

The deprecated flag was removed in this commit https://github.com/phpstan/phpstan/commit/12545aca186fe3858a88ee49494c4a589845773c

Update obsolete phpstan --errorFormat flag with correct one

---

classes/phing/types/AbstractFileSet.php

Added missing circular reference check to `AbstractFileSet::hasPatterns()` and `AbstractFileSet::hasSelectors()`

Added circular reference check.

---

classes/phing/system/io/StringReader.php

StringReader should be an InputStreamReader

---

.travis.yml

This PR wants to add a Build-Matrix to make the travis file more readable and group the tests.
As a result
- as first step the composer.json and composer.lock are validated
- as second step the coding style is checked
- for each PHP version the project is installed with lowest and normal dependency versions
- for each PHP version PHPUnit is run without XDebug to make the tests faster
- an additional test is run on the nightly build of PHP without dependency limits
- as last step PHPUnit is run with XDebug
This PR is related to PR #1129.

add Build-Matrix

---

classes/phing/listener/DefaultLogger.php

PSR12 - Blank lines may be added to improve readability and to indicate related blocks of code
Object Calisthenics - Don’t use “Else” keyword
empty - Determines whether the variable is empty or null.

PSR12 and Object Calisthenics

---

.gitattributes
.gitignore

There are some *.test files in this project. These got the line endings changed on my windows system. To prevent this, I added the to the .gitattrbutes file.
There also a *.log.txt file was generated somehow (I dont remember). Like the *.log files I added these files to the .gitignore file.

add *.test to .gitattributes

---

classes/phing/tasks/system/EchoTask.php

Fixed bool assumption for not typed hinted setters.
Related to #1201

[EchoTask] Fixed type handling.

---

classes/phing/tasks/ext/XmlPropertyTask.php
classes/phing/tasks/system/PropertyTask.php
docs/guide/en/source/appendixes/coretasks.xml
etc/phing-grammar.rng
test/classes/phing/tasks/PropertyTaskTest.php
test/etc/tasks/property.xml

Whether the build should fail on missing property file.

[PropertyTask] Added "required" attribute

---

classes/phing/tasks/system/PhingCallTask.php

Added missing `setTarget` call on the callee.
Related to #1241

[PhingCallTask] set target on callee

---

classes/phing/tasks/ext/svn/SvnBaseTask.php
docs/guide/en/source/appendixes/optionaltasks.xml
etc/phing-grammar.rng
test/classes/phing/tasks/ext/svn/SvnExportTaskTest.php
test/etc/tasks/ext/svn/SvnExportTest.xml

In some cases i need set _--config-option_ switch for svn commands (ex. _--config-option config:miscellany:use-commit-times=yes_). This PR add configOption property for all svn tasks.

Provide --config-option switch for svn tasks

---

classes/phing/tasks/system/ExecTask.php
classes/phing/types/environment/EnvVariable.php
test/classes/phing/tasks/system/ExecTaskTest.php
test/etc/tasks/system/ExecTest.xml

@jawira would you mind have a look if this would work for you?
Related to #1253

[ExecTask] Fixed resolving env vars

---

classes/phing/tasks/ext/ZipTask.php
test/classes/phing/tasks/ext/ZipUnzipTaskTest.php
test/etc/tasks/ext/ZipUnzipTaskTest.xml

[ZipTask] fixed basedir

---

test/classes/phing/tasks/condition/PhingTaskTest.php

[PhingTask] Added some more tests

---

classes/phing/tasks/system/MoveTask.php

As seen in the manual - `overwrite` should be turned on by default.

[MoveTask] Fixed default overwrite behavior.

---

classes/phing/tasks/system/TruncateTask.php
test/classes/phing/tasks/system/TruncateTaskTest.php
test/etc/tasks/system/TruncateTaskTest.xml

Using a unit for length or adjust is not possible.
Something like this was fixed:
```xml
<truncate file="foo" length="1k"/>
```

[TruncateTask] fixed unit suffix on length/adjust

---

test/classes/phing/tasks/condition/PhingTaskTest.php

[PhingTask] Added reference inheritance test

---

classes/phing/util/FileUtils.php
test/classes/phing/util/FileUtilsTest.php

Added granularity support for copyFile (the number of seconds leeway to give before deciding a file is out of date).

[FileUtils] Added granularity support

---

classes/phing/tasks/system/MoveTask.php

Preserve permissions from copy task was not taken at all i.e.
`<move preservepermissions="false" `... was not possible.

[MoveTask] Added preservepermissions support.

---

classes/phing/tasks/system/CopyTask.php
etc/phing-grammar.rng
test/classes/phing/tasks/system/CopyTaskTest.php
test/etc/tasks/system/CopyTaskTest.xml

Get control over the last modified time of the source files. Setting a granularity value will cause the assumption that the source file is x seconds older.

[CopyTask] Added granularity support on LMT of src

---

classes/phing/tasks/ext/HttpGetTask.php
classes/phing/tasks/ext/HttpRequestTask.php
classes/phing/tasks/ext/HttpTask.php
classes/phing/tasks/ext/visualizer/VisualizerTask.php
classes/phing/util/FileUtils.php
composer.json
composer.lock
test/classes/phing/tasks/ext/HTTP/BaseHttpTaskTest.php
test/classes/phing/tasks/ext/HTTP/HttpGetTaskTest.php
test/classes/phing/tasks/ext/HTTP/HttpRequestTaskTest.php
test/etc/tasks/ext/http/httpget.xml
test/etc/tasks/ext/http/httprequest.xml

Fixes #1160.
What do you think @siad007 @kenguest ?

Replace HTTP_Request2 with GuzzleHttp

---

classes/phing/tasks/system/PhingTask.php
composer.lock
etc/phing-grammar.rng
test/classes/phing/tasks/condition/PhingTaskTest.php

Log output to a file:
```
<phing phingfile="phing.xml" target="dummy" output="test.log" />
```
Related to #1241

[PhingTask] Added output argument.

---

classes/phing/tasks/system/ForeachTask.php
classes/phing/tasks/system/PhingTask.php
test/classes/phing/tasks/condition/PhingTaskTest.php

Fixed following behavior:
```xml
<target name="multi-same-property">
<phing phingfile="phing.xml" target="echo-for-multi-same">
<property name="prop" value="one"/>
<property name="prop" value="two"/>
</phing>
</target>
<target name="echo-for-multi-same">
<echo>prop is ${prop}</echo>
</target>
```
will output:
```
prop is one
prop is one
```
Related to #1241

[PhingTask] Fixed multi same property

---

classes/phing/Phing.php
classes/phing/mappers/CutDirsMapper.php
classes/phing/system/io/PhingFile.php
classes/phing/tasks/ext/property/PathToFileSet.php
classes/phing/tasks/system/ApplyTask.php
classes/phing/tasks/system/PathConvert.php
classes/phing/types/Commandline.php
classes/phing/util/DirectoryScanner.php
classes/phing/util/FileUtils.php

[FileUtils] Fixed file separator/pathSeparator as not always set.

---

classes/phing/filters/ClassConstants.php
classes/phing/tasks/system/PropertyTask.php
classes/phing/types/FilterChain.php
test/classes/phing/filters/ClassConstantsTest.php
test/etc/filters/classconstants.xml
test/etc/filters/constants.php

Assembles the constants declared in a PHP class in
```
key1=value1
key2=value2
```
format.
Example usage:
```php
class Foo
{
public const CONST1 = 'CONST 1';
protected const CONST2 = 'CONST 2';
private const CONST3 = 'CONST 3';
}
```
```xml
<property file="constants.php">
<filterchain>
<classconstants />
</filterchain>
</property>
<echo msg"${CONST1}"/>
<echo msg"${CONST2}"/>
<echo msg"${CONST3}"/>
```

Added ClassConstants filter

---

classes/phing/tasks/ext/phploc/PHPLocFormatterFactory.php
classes/phing/tasks/ext/phploc/PHPLocJSONFormatter.php
classes/phing/tasks/ext/phploc/PHPLocTask.php
classes/phing/tasks/ext/phploc/PHPLocXMLFormatter.php
test/classes/phing/tasks/ext/PHPLOCTaskTest.php
test/etc/tasks/ext/phploc/build.xml

* Enabled test execution under PHP >= 7.3
* Fixed PHPLoc task error
* Added json formatter

[phploc] Fixed broken task for PHP >= 7.3

---

classes/phing/tasks/ext/HttpRequestTask.php

Added missing constructor dependency if in verbose mode.

[HttpRequest] Fixed verbose mode.

---

classes/phing/PropertyHelper.php
classes/phing/tasks/ext/HttpGetTask.php
classes/phing/tasks/ext/HttpTask.php
test/classes/phing/tasks/ext/HTTP/HttpGetTaskTest.php
test/etc/tasks/ext/http/httpget.xml

After we discovered that we have an expandable variable, we give it back unchecked. We should return null in case of having a not expandable property.
Fixes #1391

Variable properties which could not expanded should be null.

---

classes/phing/tasks/ext/sonar/SonarConfigurationFileParser.php
test/classes/phing/tasks/ext/sonar/SonarConfigurationFileParserTest.php

Fixes #1424
Use preg_split ("/\r?\n/", $contents) instead of expand ("\n", $contents) to
account for files which use CRLF or LF (aka newline) as the line
termination character.
Previous failures on Windows:
[phpunit] Testsuite: SonarConfigurationFileParserTest
[phpunit] Tests run: 13, Warnings: 1, Failures: 7, Errors: 0, Incomplete: 0, Skipped: 0, Time elapsed: 0.37023 s
[phpunit] testPropertyWithColonAndWithoutWhitespace FAILED
[phpunit] Failed asserting that an array contains 'bar'.
[phpunit] testPropertyWithColonAndWithWhitespace FAILED
[phpunit] Failed asserting that an array contains 'bar'.
[phpunit] testPropertyWithEqualsSignAndWithoutWhitespace FAILED
[phpunit] Failed asserting that an array contains 'bar'.
[phpunit] testPropertyWithEqualsSignAndWithWhitespace FAILED
[phpunit] …

SonarConfigurationFileParser tests fail on cygwin (Windows)

---

test/classes/phing/tasks/ext/CoverageMergeTest.php
test/etc/tasks/ext/coverage/build.xml
test/etc/tasks/ext/coverage/test-1/src/Dummy1.php
test/etc/tasks/ext/coverage/test-1/test/Dummy1Test.php
test/etc/tasks/ext/coverage/test-2/src/Dummy2.php
test/etc/tasks/ext/coverage/test-2/test/Dummy2Test.php
test/etc/tasks/ext/coverage/test-3/src/Dummy3.php
test/etc/tasks/ext/coverage/test-3/test/Dummy3Test.php

Merge code coverage from different test suites.
Related to #1431

Added coverage-* related test setup

---

classes/phing/tasks/ext/phpunit/PHPUnitTask.php

Added missing
* haltondefect
* haltonwarning
* haltonrisky
Should be used by some phpunit formatters.

[PHPUnitTask] Added missing halton* methods.

---

classes/phing/tasks/ext/phpunit/PHPUnitTestRunner8.php
composer.lock
test/classes/phing/tasks/ext/CoverageMergeTest.php

Fixed code coverage in CoverageMerger Task and fixed wrong test assertion to cover empty db entries.
Related to #1430 and https://github.com/phingofficial/task-coverage/pull/2

[CoverageMergerTask] Fixed code coverage handling

---

.travis.yml
classes/phing/filters/StripPhpComments.php
composer.json
composer.lock
test/classes/phing/filters/util/StripPhpCommentsTest.php

* removed deprecated `--no-suggest`
* removed not installable 8.1snapshot
* pin lowest supported version of `mikey179/vfsstream` to 1.6.8, which fixed some curley bracets

[core] Work on PHP 8

---

test/etc/tasks/system/ExecTest.xml

Changed argument passed to phploc in testNestedEnv from -V to -v. phploc
7.x doesn't support -V anymore.

Changed arg passed to phploc

---

classes/phing/types/selectors/DateSelector.php
test/classes/phing/types/selectors/DateSelectorTest.php
test/etc/types/selectors/DateSelectorTest.xml

Fixes #1458, #1459, #1461, #1462
- Correct check of return value from array_search() in setWhen() #1458
- Correct check of return value from strtotime() in setDatetime() #1459
- Change PHPDoc for setGranularity to reflect that it uses seconds #1461
- Divide by 1000, not multipy in setMillis to convert to seconds #1462

[DateSelector] Add tests and correct behavior

---

classes/phing/listener/AnsiColorLogger.php
classes/phing/listener/HtmlColorLogger.php
classes/phing/tasks/system/CvsPassTask.php

Private methods cannot be final as they are never overridden by other classes

[php 8.0 compat] fix php warning:  Private methods cannot be final

---

classes/phing/IntrospectionHelper.php

Patch for revision 2.x
This is break on php 8.0
@siad007 @mrook

[php 8.0 compatability] deprecated ReflectionParameter::getType()

---

src/Phing/Io/FileSystem.php
src/Phing/Util/Timer.php
tests/Phing/Io/FileSystemTest.php
tests/classes/phing/tasks/ext/SassTask/Integration/SassCompilerTest.php

Fixed an issue that affects all filesystem manipulation tasks dealing with files and directories with all-numeric names and often causes build failures and/or infinite directory traversal loops. Added a simple test for the fix.
Fixed the FailOnError test bug.

[SassTask] [core] - Fixed Filesystem::listContents for numeric filenames.

---

src/Phing/Task/System/Property/PropertySelector.php
tests/Phing/Task/System/Property/PropertySelectorTest.php
tests/etc/tasks/ext/property/PropertySelectorTest.xml

Fixes and closes #1532 also changed group selctor to `$` instead of `\`.

[PropertySelector] Fixed group selection

---

src/Phing/PropertyHelper.php
src/Phing/Util/PregEngine.php

* `strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated`
* `preg_split(): Passing null to parameter #2 ($subject) of type string is deprecated`
Related to https://github.com/phingofficial/phing/pull/1534/checks?check_run_id=1894970221

[core] Fixed deprecation warnings - PHP ^8.1

---

src/Phing/Listener/DefaultLogger.php
src/Phing/Listener/JsonLogger.php
src/Phing/Listener/ProfileLogger.php
src/Phing/Listener/ProgressLogger.php
src/Phing/Listener/TargetLogger.php
src/Phing/Listener/XmlLogger.php
src/Phing/Phing.php
src/Phing/Task/System/RecorderEntry.php
src/Phing/Task/System/TouchTask.php
tests/Phing/PhingTest.php

I remove `\Phing\Phing::currentTimeMillis` function since it can be easily replaced by 'microtime(true)'

Remove currentTimeMillis

---

Dockerfile

`WORKDIR` already does `mkdir` internally.

Dockerfile: Remove superfluous mkdir

---

src/Phing/Listener/AnsiColorLogger.php
src/Phing/Listener/DefaultLogger.php
src/Phing/Listener/JsonLogger.php
src/Phing/Listener/ProfileLogger.php
src/Phing/Listener/ProgressLogger.php
src/Phing/Listener/TargetLogger.php
src/Phing/Listener/TimestampedLogger.php
src/Phing/Listener/XmlLogger.php
src/Phing/Util/ProjectTimerMap.php
src/Phing/Util/StatisticsReport.php
tests/Phing/Listener/StatisticsListenerTest.php

* Fixed bug in StatisticsReport when using a StatisticsListener in conjunction with a Xml/JsonLogger
* TimestampedLogger extends now the AnsiColorLogger also.
* Made use of DefaultClock in DefaultLogger constructor providing timer function for all Loggers

[Logger] Fixed StatisticsReport

---

tests/etc/tasks/ext/pdepend/test.php

Without a comment pdepend will raise an error.
```
preg_match_all(): Passing null to parameter #2 ($subject) of type string is deprecated
```

Add comment in test to prevent php8.1 compat issue

---

src/Phing/Io/BufferedReader.php
src/Phing/Io/File.php
src/Phing/Io/IniFileParser.php
src/Phing/Task/System/Pdo/DefaultPDOQuerySplitter.php
src/Phing/Task/System/Pdo/PDOSQLExecTask.php
src/Phing/Util/StringHelper.php
tests/Phing/Task/Optional/PDODelimitersTest.php
tests/Phing/Task/Optional/PHPMDTaskTest.php

* Skipping some test cases for dependency which will fail on PHP 8.1 and are not part of phing
* Some changes depends on PHP  compat issues

[core] PHP compat issues

---

build/build-file-linter.xml
composer.json
composer.lock
etc/default.tasks.properties
src/Phing/Task/System/XmlLintTask.php
tests/Phing/Task/System/XmlLintTaskTest.php
tests/etc/tasks/system/XmlLintTaskTest.xml

* Added improved error logging
* Moved task to system tasks
* Added test
* Added build file linter

[XmlLintTask] Added error logs.

---

etc/phing-grammar.rng
src/Phing/Task/Optional/PhpCSTask.php
tests/Phing/Task/Optional/PhpCSTaskTest.php
tests/etc/tasks/ext/phpcs/build.xml

This brings the phpcs task in line with most of the attributes used/specified in the phpcodesniffer task, making it easier to switch to the newer task.

Add support for setting standard, outfile and format to phpcs task

---

classes/phing/tasks/ext/phpdoc/PhingPhpDocumentorSetup.php
classes/phing/util/FileUtils.php

Fixed the case where a parameter with a default value followed by a required parameter was deprecated in PHP 8.0.0 and later.
Reference: https://www.php.net/manual/en/migration80.deprecated.php

Remove the default value before the required parameter.

---

etc/phing-grammar.rng
src/Phing/Task/System/Pdo/DefaultPDOQuerySplitter.php
src/Phing/Task/System/Pdo/DummyPDOQuerySplitter.php
src/Phing/Task/System/Pdo/PDOQuerySplitter.php
src/Phing/Task/System/Pdo/PDOSQLExecFormatterElement.php
src/Phing/Task/System/Pdo/PDOSQLExecTask.php
src/Phing/Task/System/Pdo/PlainPDOResultFormatter.php
tests/Phing/Task/Optional/PDOTaskTest.php
tests/etc/tasks/ext/pdo/test.xml

* Added attribute `keepformat`
* Added attribute `expandproperties`
* Added formatter attribute `showtrailers`
This will be documented in https://github.com/phingofficial/guide/issues/39

[pdosqlexec] Added more attributes.

---

etc/phing-grammar.rng
src/Phing/Task/System/Pdo/PDOSQLExecTask.php
src/Phing/Task/System/Pdo/PDOTask.php
tests/Phing/Task/Optional/PDOTaskTest.php
tests/etc/tasks/ext/pdo/test.xml

* Added failOnConnectionError
* Removed not used caching attribute

[pdosqlexec] Added failOnConnectionError / Removed obsolete caching attribute

---

build/manifest.xml

composer.json states `^7.3 || ^7.4 || ^8.0` as PHP version requirement,
so the Phar is supposed to be compatible with PHP 8.0 as well.  Since
`^7.3` implies compatibility with PHP 7.4, we don't add it explicitly
here.

Update PHP requirement in Phar manifest

---

src/Phing/Type/FileList.php

Fixed deprecated message:
```
Return type of Phing\Type\FileList::getIterator() should either be compatible with IteratorAggregate::getIterator():Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/phing/phing/src/Phing/Type/FileList.php:88
```

PHP 8.1 compatibility

---

classes/phing/tasks/system/PropertyTask.php

Fix a potential bug with PHP8 when `PropertyTask` try to resolve a boolean value.
---
In a project with Propel 1.6 and Phing 2.17 that I would like to upgrade to PHP8.  
I have some PHP Error when `PropertyTask` load the default `default.properties` file.  
```
[PHP Error] Trying to access array offset on value of type bool [line 268 of /usr/local/lib/php/phing/util/StringHelper.php]
```
I found the trouble was when `PropertyTask` try to resolve properties.  
When `true` is set, the property value is a boolean.  
And during the resolution process, `StringHelper::substring()` is called with `$value = true`.
So, a `[PHP Error]` is triggered at `StringHelper:268` because `strlen(true)` return `1`.
```ini
propel.packageObjectModel = true
propel.useDateTimeClass = true
```

Fix potential bug with StringHelper::substring() when $value is boolean

---

classes/phing/listener/DefaultLogger.php

Hello!
Try run on php 8.1 cause errors
@siad007 @mrook

fix error: implicit conversion from float to int loses precision

---

classes/phing/tasks/system/DeleteTask.php

Version: 2.17.x
This PR prevents the following error 
```
Fatal error: Uncaught Error: DeleteTask::removeFiles(): Argument #3 ($dirs) cannot be passed by reference in .../vendor/phing/phing/classes/phing/tasks/system/DeleteTask.php:205
```
Would it be possible to also release a new 2.17.x version? It would be terrific :)

DeleteTask: fix invalid passing argument by reference

---

classes/phing/tasks/system/condition/HttpCondition.php

Removed undefined constant FILTER_FLAG_SCHEME_REQUIRED for PHP 8 support

Removed undefined constant FILTER_FLAG_SCHEME_REQUIRED for PHP 8 support

---

src/Phing/Task/Ext/Analyzer/composer.json

Completely remove references to `phpcpd` and `phploc`, else phing will fail after a composer update.

Remove phpcpd and phploc refernce from composer.json

---

.php-cs-fixer.dist.php

Allows php-cs-fixer's finder to resolve `src/Phing` and `tests/Phing` with full absolute paths, so it works regardless of current directory (like when invoked from an IDE plug-in for a single file. Ex: VS-Code)

Fix(php-cs-fixer.dist.php): Use absolute paths from __DIR__

---

etc/phing-grammar.rng
src/Phing/Task/System/ReplaceRegexpTask.php
tests/Phing/Test/Task/System/ReplaceRegexpTaskTest.php
tests/etc/tasks/system/ReplaceRegexpTaskTest.xml

`ReplaceRegexpTask` does not support a `failOnError` and just log them as a warning.
* Added `failOnError` attribute with default `false`
* Changed loglevel from warning to error

[ReplaceRegexpTask] Added failOnError support

---

composer.json

This PR recreates PR #1831 which I mistakenly closed thinking it to be obsolete. If accepted, this PR updates the allowed versions of the dependency `sebastian/version` allowing `phing` to be used in projects which wish to use phpunit version 11.x for testing.
Note because `phing `uses `phpunit` version 9 for unit testing which depends on `sebastian/version` version 3.x running unit tests alone is not a sufficient test of this dependency change. Instead a project needs to be created using `phing` and `phpunit` (at version 11) and the `build.xml` needs to include a target which invokes `Phing::getPhingVersion`. I've tried this in a closed source project but can come up with a stripped down example if desired.

Allow new version of sebastian/version for phpunit 11 compatibility

---

src/Phing/Listener/DisguiseLogger.php
tests/Phing/Test/Listener/DisguiseLoggerTest.php

Related to #1672 
* Added `DisguiseLogger`
Using this logger prevents output logging for passwords in URIs and mask them with `*****`
**build.xml**
```
<project name="Test" default="test" basedir=".">
<target name="test">
<echo msg="some text and a link to http://foo:bar@example.com/baz?one=two" />
</target>
</project>
```
**using logger**
```
phing -logger "Phing\Listener\DisguiseLogger" -f build.xml
```
**output**
```
[echo] some text and a link to http://foo:*****@example.com/baz?one=two
```

Introduce DisguiseLogger

---

.github/workflows/build.yml

See for reference: https://github.com/phingofficial/phing/actions/runs/12104908943/job/33749537007
Added condition to ignore the dependabot actor for the docker build image step.

Fixed failing dependabot workflow runs

---

src/Phing/Phing.php

Added cache to the existing `Phing::getPhingVersion()` call and added a cached `Phing::getPhingShortVersion()` method to get rid of unnecessary name part stripping.

[Phing] Cache Phing::phingVersion() and add cached Phing::phingShortVersion() method
